// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `StepAuthorization` in stride_core.
enum PlatformAuthorization: Int, CaseIterable {
  case granted = 0
  case denied = 1
  case unavailable = 2
}

/// Mirrors `CursorStatus` in stride_core.
enum PlatformCursorStatus: Int, CaseIterable {
  case valid = 0
  case invalidated = 1
}

/// An authoritative re-read of a bounded window, sent only when the cursor was
/// invalidated. See `StepRescan` in stride_core for the recovery strategy.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformRescan: Hashable, CustomStringConvertible {
  /// Start of the rescanned window — the watermark the caller supplied,
  /// clamped by the adapter to its maximum window.
  var windowStartMillis: Int64
  var windowEndMillis: Int64
  /// The authoritative total for the window. A total, not a delta: after cursor
  /// loss only an absolute figure can be reconciled against what was already
  /// granted.
  var windowTotal: Int64
  /// True when the window was clamped, leaving an unreachable gap. Those steps
  /// are recorded, never granted — inventing progress is worse than missing it.
  var truncated: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformRescan? {
    let windowStartMillis = pigeonVar_list[0] as! Int64
    let windowEndMillis = pigeonVar_list[1] as! Int64
    let windowTotal = pigeonVar_list[2] as! Int64
    let truncated = pigeonVar_list[3] as! Bool

    return PlatformRescan(
      windowStartMillis: windowStartMillis,
      windowEndMillis: windowEndMillis,
      windowTotal: windowTotal,
      truncated: truncated
    )
  }
  func toList() -> [Any?] {
    return [
      windowStartMillis,
      windowEndMillis,
      windowTotal,
      truncated,
    ]
  }
  static func == (lhs: PlatformRescan, rhs: PlatformRescan) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.windowStartMillis, rhs.windowStartMillis) && MessagesPigeonInternal.deepEquals(lhs.windowEndMillis, rhs.windowEndMillis) && MessagesPigeonInternal.deepEquals(lhs.windowTotal, rhs.windowTotal) && MessagesPigeonInternal.deepEquals(lhs.truncated, rhs.truncated)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformRescan")
    MessagesPigeonInternal.deepHash(value: windowStartMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: windowEndMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: windowTotal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: truncated, hasher: &hasher)
  }

  public var description: String {
    return "PlatformRescan(windowStartMillis: \(String(describing: windowStartMillis)), windowEndMillis: \(String(describing: windowEndMillis)), windowTotal: \(String(describing: windowTotal)), truncated: \(String(describing: truncated)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformFetchResult: Hashable, CustomStringConvertible {
  var status: PlatformCursorStatus
  /// A true delta only when [status] is `valid`. Meaningless otherwise.
  var newSteps: Int64
  /// Steps removed by corrections since the cursor. Information, not an
  /// instruction — reconciliation never revokes granted progress.
  var deletedSteps: Int64
  /// Opaque. An archived HKQueryAnchor on iOS, a changes token on Android.
  /// The caller stores and returns it without inspecting it, and persists it
  /// only after the resulting batch is committed to the ledger.
  var cursor: FlutterStandardTypedData? = nil
  var rescan: PlatformRescan? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformFetchResult? {
    let status = pigeonVar_list[0] as! PlatformCursorStatus
    let newSteps = pigeonVar_list[1] as! Int64
    let deletedSteps = pigeonVar_list[2] as! Int64
    let cursor: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])
    let rescan: PlatformRescan? = nilOrValue(pigeonVar_list[4])

    return PlatformFetchResult(
      status: status,
      newSteps: newSteps,
      deletedSteps: deletedSteps,
      cursor: cursor,
      rescan: rescan
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      newSteps,
      deletedSteps,
      cursor,
      rescan,
    ]
  }
  static func == (lhs: PlatformFetchResult, rhs: PlatformFetchResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.newSteps, rhs.newSteps) && MessagesPigeonInternal.deepEquals(lhs.deletedSteps, rhs.deletedSteps) && MessagesPigeonInternal.deepEquals(lhs.cursor, rhs.cursor) && MessagesPigeonInternal.deepEquals(lhs.rescan, rhs.rescan)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformFetchResult")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: newSteps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deletedSteps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cursor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rescan, hasher: &hasher)
  }

  public var description: String {
    return "PlatformFetchResult(status: \(String(describing: status)), newSteps: \(String(describing: newSteps)), deletedSteps: \(String(describing: deletedSteps)), cursor: \(String(describing: cursor)), rescan: \(String(describing: rescan)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAuthorization(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformCursorStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PlatformRescan.fromList(self.readValue() as! [Any?])
    case 132:
      return PlatformFetchResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformAuthorization {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformCursorStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformRescan {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformFetchResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HealthHostApi {
  /// Whether the platform's health service is present and usable. False on
  /// Android without Health Connect installed — a normal state, not an error.
  func isAvailable() throws -> Bool
  func requestAuthorization(completion: @escaping (Result<PlatformAuthorization, Error>) -> Void)
  /// Fetch steps since [cursor]. [watermarkMillis] bounds the rescan window if
  /// the cursor turns out to be invalid.
  func fetchNewSteps(cursor: FlutterStandardTypedData?, watermarkMillis: Int64?, completion: @escaping (Result<PlatformFetchResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HealthHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HealthHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HealthHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether the platform's health service is present and usable. False on
    /// Android without Health Connect installed — a normal state, not an error.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_health.HealthHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_health.HealthHostApi.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { _, reply in
        api.requestAuthorization { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
    /// Fetch steps since [cursor]. [watermarkMillis] bounds the rescan window if
    /// the cursor turns out to be invalid.
    let fetchNewStepsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_health.HealthHostApi.fetchNewSteps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchNewStepsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cursorArg: FlutterStandardTypedData? = nilOrValue(args[0])
        let watermarkMillisArg: Int64? = nilOrValue(args[1])
        api.fetchNewSteps(cursor: cursorArg, watermarkMillis: watermarkMillisArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchNewStepsChannel.setMessageHandler(nil)
    }
  }
}
