// GENERATED by Scripts/art/package-art.js — do not edit by hand.
//
// Where each sprite meets the ground, in sprite-local pixel coordinates.
//
// This table is what makes the contact shadow *derived from the sprite* rather
// than tuned per scene. A caller places a sprite; it never supplies a shadow
// width, so the shadow cannot disagree with the figure standing on it.
//
// Measured across the lowest four opaque rows of the sprite, which is the part
// touching the ground — not the opaque bounding box, which would include the
// head and the backpack.
library;

/// The ground-contact span of one sprite.
final class SpriteFootprint {
  const SpriteFootprint({
    required this.left,
    required this.right,
    required this.bottom,
  });

  /// Leftmost contact column, sprite-local.
  final int left;

  /// Rightmost contact column, sprite-local.
  final int right;

  /// The sprite's lowest opaque row.
  final int bottom;

  /// Contact width in sprite pixels.
  int get width => right - left + 1;

  /// The horizontal centre of the contact span, sprite-local.
  double get centerX => (left + right + 1) / 2;
}

abstract final class SpriteFootprints {
  /// `traveler_south` — 24 px of contact, 19..42.
  static const SpriteFootprint travelerSouth = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `gather` — 24 px of contact, 19..42.
  static const SpriteFootprint gather = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 63,
  );

  /// `ambient_traveler_stretch` — 24 px of contact, 27..50.
  static const SpriteFootprint ambientTravelerStretch = SpriteFootprint(
    left: 27,
    right: 50,
    bottom: 62,
  );

  /// `ambient_traveler_drink` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerDrink = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_eat` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerEat = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_pack_check` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerPackCheck = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_axe_inspect` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerAxeInspect = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_head_scratch` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerHeadScratch = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_wipe_brow` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerWipeBrow = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_sit_ground` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerSitGround = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_pushups_side` — 12 px of contact, 34..45.
  static const SpriteFootprint ambientTravelerPushupsSide = SpriteFootprint(
    left: 34,
    right: 45,
    bottom: 62,
  );

  /// `ambient_traveler_dangle_string` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerDangleString = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_crouch_pet` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerCrouchPet = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_pair_pet_cat` — 55 px of contact, 20..74.
  static const SpriteFootprint ambientPairPetCat = SpriteFootprint(
    left: 20,
    right: 74,
    bottom: 62,
  );

  /// `ambient_cat_stand` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatStand = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_walk` — 19 px of contact, 8..26.
  static const SpriteFootprint ambientCatWalk = SpriteFootprint(
    left: 8,
    right: 26,
    bottom: 27,
  );

  /// `ambient_cat_walk_west` — 17 px of contact, 14..30.
  static const SpriteFootprint ambientCatWalkWest = SpriteFootprint(
    left: 14,
    right: 30,
    bottom: 27,
  );

  /// `ambient_cat_sit_down` — 16 px of contact, 9..24.
  static const SpriteFootprint ambientCatSitDown = SpriteFootprint(
    left: 9,
    right: 24,
    bottom: 27,
  );

  /// `ambient_cat_settle` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatSettle = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_lie_rest` — 19 px of contact, 12..30.
  static const SpriteFootprint ambientCatLieRest = SpriteFootprint(
    left: 12,
    right: 30,
    bottom: 27,
  );

  /// `ambient_cat_roll` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatRoll = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_bat_yarn` — 25 px of contact, 8..32.
  static const SpriteFootprint ambientCatBatYarn = SpriteFootprint(
    left: 8,
    right: 32,
    bottom: 27,
  );

  /// `ambient_cat_stretch` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatStretch = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_prop_fire` — 15 px of contact, 8..22.
  static const SpriteFootprint ambientPropFire = SpriteFootprint(
    left: 8,
    right: 22,
    bottom: 28,
  );

  /// `ambient_prop_yarn` — 13 px of contact, 2..14.
  static const SpriteFootprint ambientPropYarn = SpriteFootprint(
    left: 2,
    right: 14,
    bottom: 12,
  );

  /// `ambient_traveler_read` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerRead = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_pick_inspect` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerPickInspect = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `combat_traveler_combat_idle` — 12 px of contact, 28..39.
  static const SpriteFootprint combatTravelerCombatIdle = SpriteFootprint(
    left: 28,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_attack` — 12 px of contact, 34..45.
  static const SpriteFootprint combatTravelerAttack = SpriteFootprint(
    left: 34,
    right: 45,
    bottom: 62,
  );

  /// `combat_traveler_hit` — 11 px of contact, 27..37.
  static const SpriteFootprint combatTravelerHit = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 62,
  );

  /// `combat_wolf_idle` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfIdle = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_wolf_attack` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfAttack = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_wolf_hit` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfHit = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_goblin_idle` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinIdle = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_goblin_attack` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinAttack = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_goblin_hit` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinHit = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_guardian_idle` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianIdle = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_attack` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianAttack = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_swipe` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianSwipe = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_hit` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianHit = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_wolf_defeat` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfDefeat = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_goblin_defeat` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinDefeat = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_guardian_defeat` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianDefeat = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );
}
