// GENERATED by Scripts/art/package-art.js — do not edit by hand.
//
// Where each sprite meets the ground, in sprite-local pixel coordinates.
//
// This table is what makes the contact shadow *derived from the sprite* rather
// than tuned per scene. A caller places a sprite; it never supplies a shadow
// width, so the shadow cannot disagree with the figure standing on it.
//
// Measured across the lowest four opaque rows of the sprite, which is the part
// touching the ground — not the opaque bounding box, which would include the
// head and the backpack.
library;

/// The ground-contact span of one sprite.
final class SpriteFootprint {
  const SpriteFootprint({
    required this.left,
    required this.right,
    required this.bottom,
  });

  /// Leftmost contact column, sprite-local.
  final int left;

  /// Rightmost contact column, sprite-local.
  final int right;

  /// The sprite's lowest opaque row.
  final int bottom;

  /// Contact width in sprite pixels.
  int get width => right - left + 1;

  /// The horizontal centre of the contact span, sprite-local.
  double get centerX => (left + right + 1) / 2;
}

abstract final class SpriteFootprints {
  /// `traveler_south` — 24 px of contact, 19..42.
  static const SpriteFootprint travelerSouth = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `gather` — 24 px of contact, 19..42.
  static const SpriteFootprint gather = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 63,
  );

  /// `ambient_traveler_stretch` — 24 px of contact, 27..50.
  static const SpriteFootprint ambientTravelerStretch = SpriteFootprint(
    left: 27,
    right: 50,
    bottom: 62,
  );

  /// `ambient_traveler_drink` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerDrink = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_eat` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerEat = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_pack_check` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerPackCheck = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_axe_inspect` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerAxeInspect = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_head_scratch` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerHeadScratch = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_wipe_brow` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerWipeBrow = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_sit_ground` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerSitGround = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_pushups_side` — 12 px of contact, 34..45.
  static const SpriteFootprint ambientTravelerPushupsSide = SpriteFootprint(
    left: 34,
    right: 45,
    bottom: 62,
  );

  /// `ambient_traveler_dangle_string` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerDangleString = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_crouch_pet` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerCrouchPet = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_pair_pet_cat` — 55 px of contact, 20..74.
  static const SpriteFootprint ambientPairPetCat = SpriteFootprint(
    left: 20,
    right: 74,
    bottom: 62,
  );

  /// `ambient_cat_stand` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatStand = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_walk` — 19 px of contact, 8..26.
  static const SpriteFootprint ambientCatWalk = SpriteFootprint(
    left: 8,
    right: 26,
    bottom: 27,
  );

  /// `ambient_cat_walk_west` — 17 px of contact, 14..30.
  static const SpriteFootprint ambientCatWalkWest = SpriteFootprint(
    left: 14,
    right: 30,
    bottom: 27,
  );

  /// `ambient_cat_sit_down` — 16 px of contact, 9..24.
  static const SpriteFootprint ambientCatSitDown = SpriteFootprint(
    left: 9,
    right: 24,
    bottom: 27,
  );

  /// `ambient_cat_settle` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatSettle = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_lie_rest` — 19 px of contact, 12..30.
  static const SpriteFootprint ambientCatLieRest = SpriteFootprint(
    left: 12,
    right: 30,
    bottom: 27,
  );

  /// `ambient_cat_roll` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatRoll = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_cat_bat_yarn` — 25 px of contact, 8..32.
  static const SpriteFootprint ambientCatBatYarn = SpriteFootprint(
    left: 8,
    right: 32,
    bottom: 27,
  );

  /// `ambient_cat_stretch` — 18 px of contact, 8..25.
  static const SpriteFootprint ambientCatStretch = SpriteFootprint(
    left: 8,
    right: 25,
    bottom: 27,
  );

  /// `ambient_prop_fire` — 15 px of contact, 8..22.
  static const SpriteFootprint ambientPropFire = SpriteFootprint(
    left: 8,
    right: 22,
    bottom: 28,
  );

  /// `ambient_prop_yarn` — 13 px of contact, 2..14.
  static const SpriteFootprint ambientPropYarn = SpriteFootprint(
    left: 2,
    right: 14,
    bottom: 12,
  );

  /// `ambient_traveler_pick_inspect` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerPickInspect = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_read` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerRead = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_idle_breathe` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerIdleBreathe = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_look_around` — 24 px of contact, 19..42.
  static const SpriteFootprint ambientTravelerLookAround = SpriteFootprint(
    left: 19,
    right: 42,
    bottom: 62,
  );

  /// `ambient_fauna_songbird_16` — 9 px of contact, 3..11.
  static const SpriteFootprint ambientFaunaSongbird16 = SpriteFootprint(
    left: 3,
    right: 11,
    bottom: 14,
  );

  /// `ambient_fauna_crow_16` — 10 px of contact, 4..13.
  static const SpriteFootprint ambientFaunaCrow16 = SpriteFootprint(
    left: 4,
    right: 13,
    bottom: 13,
  );

  /// `ambient_fauna_ptarmigan_16` — 11 px of contact, 3..13.
  static const SpriteFootprint ambientFaunaPtarmigan16 = SpriteFootprint(
    left: 3,
    right: 13,
    bottom: 12,
  );

  /// `ambient_fauna_hare_16` — 10 px of contact, 3..12.
  static const SpriteFootprint ambientFaunaHare16 = SpriteFootprint(
    left: 3,
    right: 12,
    bottom: 15,
  );

  /// `traveler_walk_west` — 8 px of contact, 22..29.
  static const SpriteFootprint travelerWalkWest = SpriteFootprint(
    left: 22,
    right: 29,
    bottom: 62,
  );

  /// `ambient_activity_woodcut` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientActivityWoodcut = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 62,
  );

  /// `ambient_activity_mine` — 13 px of contact, 28..40.
  static const SpriteFootprint ambientActivityMine = SpriteFootprint(
    left: 28,
    right: 40,
    bottom: 62,
  );

  /// `ambient_activity_forage` — 13 px of contact, 20..32.
  static const SpriteFootprint ambientActivityForage = SpriteFootprint(
    left: 20,
    right: 32,
    bottom: 62,
  );

  /// `ambient_activity_smith` — 13 px of contact, 30..42.
  static const SpriteFootprint ambientActivitySmith = SpriteFootprint(
    left: 30,
    right: 42,
    bottom: 62,
  );

  /// `ambient_activity_cook` — 13 px of contact, 21..33.
  static const SpriteFootprint ambientActivityCook = SpriteFootprint(
    left: 21,
    right: 33,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_bronzeaxe_woodcut` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerJerkinBronzeaxeWoodcut = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 62,
  );

  /// `ambient_traveler_coat_bronzeaxe_woodcut` — 13 px of contact, 35..47.
  static const SpriteFootprint ambientTravelerCoatBronzeaxeWoodcut = SpriteFootprint(
    left: 35,
    right: 47,
    bottom: 62,
  );

  /// `ambient_traveler_base_bronzeaxe_woodcut` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerBaseBronzeaxeWoodcut = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_bronzepick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerJerkinBronzepickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 62,
  );

  /// `ambient_traveler_coat_bronzepick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerCoatBronzepickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_base_bronzepick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerBaseBronzepickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_plate_bronzeaxe_woodcut` — 11 px of contact, 27..37.
  static const SpriteFootprint ambientTravelerPlateBronzeaxeWoodcut = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 62,
  );

  /// `ambient_traveler_plate_steelpick_mine` — 11 px of contact, 30..40.
  static const SpriteFootprint ambientTravelerPlateSteelpickMine = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_steelpick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerJerkinSteelpickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_coat_steelpick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerCoatSteelpickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_plate_steelaxe_woodcut` — 11 px of contact, 27..37.
  static const SpriteFootprint ambientTravelerPlateSteelaxeWoodcut = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_steelaxe_woodcut` — 13 px of contact, 37..49.
  static const SpriteFootprint ambientTravelerJerkinSteelaxeWoodcut = SpriteFootprint(
    left: 37,
    right: 49,
    bottom: 62,
  );

  /// `ambient_traveler_coat_steelaxe_woodcut` — 13 px of contact, 36..48.
  static const SpriteFootprint ambientTravelerCoatSteelaxeWoodcut = SpriteFootprint(
    left: 36,
    right: 48,
    bottom: 62,
  );

  /// `ambient_traveler_plate_forage` — 11 px of contact, 27..37.
  static const SpriteFootprint ambientTravelerPlateForage = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_forage` — 13 px of contact, 27..39.
  static const SpriteFootprint ambientTravelerJerkinForage = SpriteFootprint(
    left: 27,
    right: 39,
    bottom: 62,
  );

  /// `ambient_traveler_coat_forage` — 13 px of contact, 26..38.
  static const SpriteFootprint ambientTravelerCoatForage = SpriteFootprint(
    left: 26,
    right: 38,
    bottom: 62,
  );

  /// `ambient_traveler_plate_smith` — 13 px of contact, 30..42.
  static const SpriteFootprint ambientTravelerPlateSmith = SpriteFootprint(
    left: 30,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_smith` — 13 px of contact, 30..42.
  static const SpriteFootprint ambientTravelerJerkinSmith = SpriteFootprint(
    left: 30,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_coat_smith` — 13 px of contact, 33..45.
  static const SpriteFootprint ambientTravelerCoatSmith = SpriteFootprint(
    left: 33,
    right: 45,
    bottom: 62,
  );

  /// `ambient_traveler_plate_cook` — 13 px of contact, 21..33.
  static const SpriteFootprint ambientTravelerPlateCook = SpriteFootprint(
    left: 21,
    right: 33,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_cook` — 13 px of contact, 21..33.
  static const SpriteFootprint ambientTravelerJerkinCook = SpriteFootprint(
    left: 21,
    right: 33,
    bottom: 62,
  );

  /// `ambient_traveler_coat_cook` — 13 px of contact, 21..33.
  static const SpriteFootprint ambientTravelerCoatCook = SpriteFootprint(
    left: 21,
    right: 33,
    bottom: 62,
  );

  /// `ambient_traveler_plate_idle_breathe` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerPlateIdleBreathe = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_idle_breathe` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerJerkinIdleBreathe = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_coat_idle_breathe` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerCoatIdleBreathe = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_plate_look_around` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerPlateLookAround = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_look_around` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerJerkinLookAround = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_coat_look_around` — 24 px of contact, 20..43.
  static const SpriteFootprint ambientTravelerCoatLookAround = SpriteFootprint(
    left: 20,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_plate_walk_west` — 11 px of contact, 30..40.
  static const SpriteFootprint ambientTravelerPlateWalkWest = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_walk_west` — 12 px of contact, 31..42.
  static const SpriteFootprint ambientTravelerJerkinWalkWest = SpriteFootprint(
    left: 31,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_coat_walk_west` — 13 px of contact, 30..42.
  static const SpriteFootprint ambientTravelerCoatWalkWest = SpriteFootprint(
    left: 30,
    right: 42,
    bottom: 63,
  );

  /// `ambient_traveler_plate_bronzepick_mine` — 11 px of contact, 30..40.
  static const SpriteFootprint ambientTravelerPlateBronzepickMine = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `ambient_traveler_warden_bronzepick_mine` — 11 px of contact, 37..47.
  static const SpriteFootprint ambientTravelerWardenBronzepickMine = SpriteFootprint(
    left: 37,
    right: 47,
    bottom: 62,
  );

  /// `ambient_traveler_warden_steelpick_mine` — 11 px of contact, 35..45.
  static const SpriteFootprint ambientTravelerWardenSteelpickMine = SpriteFootprint(
    left: 35,
    right: 45,
    bottom: 62,
  );

  /// `ambient_traveler_warden_bronzeaxe_woodcut` — 11 px of contact, 32..42.
  static const SpriteFootprint ambientTravelerWardenBronzeaxeWoodcut = SpriteFootprint(
    left: 32,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_warden_steelaxe_woodcut` — 11 px of contact, 33..43.
  static const SpriteFootprint ambientTravelerWardenSteelaxeWoodcut = SpriteFootprint(
    left: 33,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_warden_forage` — 11 px of contact, 27..37.
  static const SpriteFootprint ambientTravelerWardenForage = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 63,
  );

  /// `ambient_traveler_warden_idle_breathe` — 23 px of contact, 21..43.
  static const SpriteFootprint ambientTravelerWardenIdleBreathe = SpriteFootprint(
    left: 21,
    right: 43,
    bottom: 62,
  );

  /// `ambient_traveler_warden_look_around` — 23 px of contact, 20..42.
  static const SpriteFootprint ambientTravelerWardenLookAround = SpriteFootprint(
    left: 20,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_warden_walk_west` — 11 px of contact, 27..37.
  static const SpriteFootprint ambientTravelerWardenWalkWest = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 63,
  );

  /// `ambient_traveler_warden_smith` — 13 px of contact, 30..42.
  static const SpriteFootprint ambientTravelerWardenSmith = SpriteFootprint(
    left: 30,
    right: 42,
    bottom: 62,
  );

  /// `ambient_traveler_warden_cook` — 13 px of contact, 21..33.
  static const SpriteFootprint ambientTravelerWardenCook = SpriteFootprint(
    left: 21,
    right: 33,
    bottom: 62,
  );

  /// `ambient_traveler_plate_hornpick_mine` — 11 px of contact, 31..41.
  static const SpriteFootprint ambientTravelerPlateHornpickMine = SpriteFootprint(
    left: 31,
    right: 41,
    bottom: 62,
  );

  /// `ambient_traveler_jerkin_hornpick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerJerkinHornpickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 62,
  );

  /// `ambient_traveler_coat_hornpick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerCoatHornpickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_base_hornpick_mine` — 13 px of contact, 32..44.
  static const SpriteFootprint ambientTravelerBaseHornpickMine = SpriteFootprint(
    left: 32,
    right: 44,
    bottom: 63,
  );

  /// `ambient_traveler_warden_hornpick_mine` — 11 px of contact, 40..50.
  static const SpriteFootprint ambientTravelerWardenHornpickMine = SpriteFootprint(
    left: 40,
    right: 50,
    bottom: 62,
  );

  /// `combat_traveler_attack` — 12 px of contact, 34..45.
  static const SpriteFootprint combatTravelerAttack = SpriteFootprint(
    left: 34,
    right: 45,
    bottom: 62,
  );

  /// `combat_traveler_hit` — 11 px of contact, 27..37.
  static const SpriteFootprint combatTravelerHit = SpriteFootprint(
    left: 27,
    right: 37,
    bottom: 62,
  );

  /// `combat_wolf_idle` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfIdle = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_wolf_attack` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfAttack = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_wolf_hit` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfHit = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_goblin_idle` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinIdle = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_goblin_attack` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinAttack = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_goblin_hit` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinHit = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_guardian_idle` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianIdle = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_attack` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianAttack = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_swipe` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianSwipe = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_hit` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianHit = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_wolf_defeat` — 25 px of contact, 21..45.
  static const SpriteFootprint combatWolfDefeat = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_goblin_defeat` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGoblinDefeat = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_guardian_defeat` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianDefeat = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_traveler_stagger` — 12 px of contact, 22..33.
  static const SpriteFootprint combatTravelerStagger = SpriteFootprint(
    left: 22,
    right: 33,
    bottom: 62,
  );

  /// `combat_boar_idle` — 23 px of contact, 23..45.
  static const SpriteFootprint combatBoarIdle = SpriteFootprint(
    left: 23,
    right: 45,
    bottom: 43,
  );

  /// `combat_boar_attack` — 23 px of contact, 23..45.
  static const SpriteFootprint combatBoarAttack = SpriteFootprint(
    left: 23,
    right: 45,
    bottom: 43,
  );

  /// `combat_boar_defeat` — 23 px of contact, 23..45.
  static const SpriteFootprint combatBoarDefeat = SpriteFootprint(
    left: 23,
    right: 45,
    bottom: 43,
  );

  /// `combat_bear_idle` — 42 px of contact, 22..63.
  static const SpriteFootprint combatBearIdle = SpriteFootprint(
    left: 22,
    right: 63,
    bottom: 61,
  );

  /// `combat_bear_attack2` — 42 px of contact, 22..63.
  static const SpriteFootprint combatBearAttack2 = SpriteFootprint(
    left: 22,
    right: 63,
    bottom: 61,
  );

  /// `combat_bear_defeat` — 42 px of contact, 22..63.
  static const SpriteFootprint combatBearDefeat = SpriteFootprint(
    left: 22,
    right: 63,
    bottom: 61,
  );

  /// `combat_ram_idle` — 24 px of contact, 22..45.
  static const SpriteFootprint combatRamIdle = SpriteFootprint(
    left: 22,
    right: 45,
    bottom: 42,
  );

  /// `combat_ram_attack` — 24 px of contact, 22..45.
  static const SpriteFootprint combatRamAttack = SpriteFootprint(
    left: 22,
    right: 45,
    bottom: 42,
  );

  /// `combat_ram_defeat` — 24 px of contact, 22..45.
  static const SpriteFootprint combatRamDefeat = SpriteFootprint(
    left: 22,
    right: 45,
    bottom: 42,
  );

  /// `combat_crawler_idle` — 36 px of contact, 2..37.
  static const SpriteFootprint combatCrawlerIdle = SpriteFootprint(
    left: 2,
    right: 37,
    bottom: 40,
  );

  /// `combat_crawler_attack` — 36 px of contact, 2..37.
  static const SpriteFootprint combatCrawlerAttack = SpriteFootprint(
    left: 2,
    right: 37,
    bottom: 40,
  );

  /// `combat_lynx_idle` — 42 px of contact, 8..49.
  static const SpriteFootprint combatLynxIdle = SpriteFootprint(
    left: 8,
    right: 49,
    bottom: 39,
  );

  /// `combat_lynx_attack` — 42 px of contact, 8..49.
  static const SpriteFootprint combatLynxAttack = SpriteFootprint(
    left: 8,
    right: 49,
    bottom: 39,
  );

  /// `combat_lynx_defeat` — 42 px of contact, 8..49.
  static const SpriteFootprint combatLynxDefeat = SpriteFootprint(
    left: 8,
    right: 49,
    bottom: 39,
  );

  /// `combat_traveler_unarmed_idle` — 7 px of contact, 30..36.
  static const SpriteFootprint combatTravelerUnarmedIdle = SpriteFootprint(
    left: 30,
    right: 36,
    bottom: 63,
  );

  /// `combat_traveler_unarmed_attack` — 8 px of contact, 26..33.
  static const SpriteFootprint combatTravelerUnarmedAttack = SpriteFootprint(
    left: 26,
    right: 33,
    bottom: 62,
  );

  /// `combat_traveler_unarmed_hit` — 8 px of contact, 26..33.
  static const SpriteFootprint combatTravelerUnarmedHit = SpriteFootprint(
    left: 26,
    right: 33,
    bottom: 62,
  );

  /// `combat_traveler_bronze_idle` — 12 px of contact, 38..49.
  static const SpriteFootprint combatTravelerBronzeIdle = SpriteFootprint(
    left: 38,
    right: 49,
    bottom: 62,
  );

  /// `combat_traveler_bronze_attack` — 12 px of contact, 38..49.
  static const SpriteFootprint combatTravelerBronzeAttack = SpriteFootprint(
    left: 38,
    right: 49,
    bottom: 62,
  );

  /// `combat_traveler_bronze_hit` — 12 px of contact, 38..49.
  static const SpriteFootprint combatTravelerBronzeHit = SpriteFootprint(
    left: 38,
    right: 49,
    bottom: 62,
  );

  /// `combat_traveler_unarmed_stagger` — 8 px of contact, 26..33.
  static const SpriteFootprint combatTravelerUnarmedStagger = SpriteFootprint(
    left: 26,
    right: 33,
    bottom: 62,
  );

  /// `combat_traveler_bronze_stagger` — 12 px of contact, 38..49.
  static const SpriteFootprint combatTravelerBronzeStagger = SpriteFootprint(
    left: 38,
    right: 49,
    bottom: 62,
  );

  /// `combat_traveler_combat_idle` — 11 px of contact, 31..41.
  static const SpriteFootprint combatTravelerCombatIdle = SpriteFootprint(
    left: 31,
    right: 41,
    bottom: 62,
  );

  /// `combat_boar_hit` — 23 px of contact, 23..45.
  static const SpriteFootprint combatBoarHit = SpriteFootprint(
    left: 23,
    right: 45,
    bottom: 43,
  );

  /// `combat_bear_hit` — 43 px of contact, 21..63.
  static const SpriteFootprint combatBearHit = SpriteFootprint(
    left: 21,
    right: 63,
    bottom: 61,
  );

  /// `combat_crawler_hit` — 44 px of contact, 2..45.
  static const SpriteFootprint combatCrawlerHit = SpriteFootprint(
    left: 2,
    right: 45,
    bottom: 39,
  );

  /// `combat_crawler_defeat` — 46 px of contact, 0..45.
  static const SpriteFootprint combatCrawlerDefeat = SpriteFootprint(
    left: 0,
    right: 45,
    bottom: 39,
  );

  /// `combat_old_grey_idle` — 25 px of contact, 21..45.
  static const SpriteFootprint combatOldGreyIdle = SpriteFootprint(
    left: 21,
    right: 45,
    bottom: 40,
  );

  /// `combat_old_grey_attack` — 25 px of contact, 22..46.
  static const SpriteFootprint combatOldGreyAttack = SpriteFootprint(
    left: 22,
    right: 46,
    bottom: 40,
  );

  /// `combat_gallery_foreman_idle` — 14 px of contact, 22..35.
  static const SpriteFootprint combatGalleryForemanIdle = SpriteFootprint(
    left: 22,
    right: 35,
    bottom: 46,
  );

  /// `combat_gallery_foreman_attack` — 10 px of contact, 23..32.
  static const SpriteFootprint combatGalleryForemanAttack = SpriteFootprint(
    left: 23,
    right: 32,
    bottom: 46,
  );

  /// `combat_rimeclaw_matriarch_idle` — 42 px of contact, 9..50.
  static const SpriteFootprint combatRimeclawMatriarchIdle = SpriteFootprint(
    left: 9,
    right: 50,
    bottom: 40,
  );

  /// `combat_rimeclaw_matriarch_attack` — 41 px of contact, 8..48.
  static const SpriteFootprint combatRimeclawMatriarchAttack = SpriteFootprint(
    left: 8,
    right: 48,
    bottom: 40,
  );

  /// `combat_guardian_awakened_idle` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianAwakenedIdle = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_guardian_awakened_attack` — 20 px of contact, 38..57.
  static const SpriteFootprint combatGuardianAwakenedAttack = SpriteFootprint(
    left: 38,
    right: 57,
    bottom: 83,
  );

  /// `combat_salamander_idle` — 12 px of contact, 23..34.
  static const SpriteFootprint combatSalamanderIdle = SpriteFootprint(
    left: 23,
    right: 34,
    bottom: 50,
  );

  /// `combat_salamander_attack` — 12 px of contact, 23..34.
  static const SpriteFootprint combatSalamanderAttack = SpriteFootprint(
    left: 23,
    right: 34,
    bottom: 50,
  );

  /// `combat_salamander_hit` — 12 px of contact, 23..34.
  static const SpriteFootprint combatSalamanderHit = SpriteFootprint(
    left: 23,
    right: 34,
    bottom: 50,
  );

  /// `combat_salamander_defeat` — 12 px of contact, 23..34.
  static const SpriteFootprint combatSalamanderDefeat = SpriteFootprint(
    left: 23,
    right: 34,
    bottom: 50,
  );

  /// `combat_ram2_idle` — 24 px of contact, 22..45.
  static const SpriteFootprint combatRam2Idle = SpriteFootprint(
    left: 22,
    right: 45,
    bottom: 42,
  );

  /// `combat_traveler_base_unarmed_brace` — 8 px of contact, 25..32.
  static const SpriteFootprint combatTravelerBaseUnarmedBrace = SpriteFootprint(
    left: 25,
    right: 32,
    bottom: 60,
  );

  /// `combat_traveler_base_bronze_brace` — 12 px of contact, 37..48.
  static const SpriteFootprint combatTravelerBaseBronzeBrace = SpriteFootprint(
    left: 37,
    right: 48,
    bottom: 62,
  );

  /// `combat_traveler_plate_bronze_idle` — 30 px of contact, 30..59.
  static const SpriteFootprint combatTravelerPlateBronzeIdle = SpriteFootprint(
    left: 30,
    right: 59,
    bottom: 62,
  );

  /// `combat_traveler_plate_bronze_attack` — 11 px of contact, 30..40.
  static const SpriteFootprint combatTravelerPlateBronzeAttack = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `combat_traveler_plate_bronze_hit` — 27 px of contact, 34..60.
  static const SpriteFootprint combatTravelerPlateBronzeHit = SpriteFootprint(
    left: 34,
    right: 60,
    bottom: 62,
  );

  /// `combat_traveler_plate_bronze_stagger` — 35 px of contact, 25..59.
  static const SpriteFootprint combatTravelerPlateBronzeStagger = SpriteFootprint(
    left: 25,
    right: 59,
    bottom: 63,
  );

  /// `combat_traveler_plate_bronze_brace` — 10 px of contact, 33..42.
  static const SpriteFootprint combatTravelerPlateBronzeBrace = SpriteFootprint(
    left: 33,
    right: 42,
    bottom: 62,
  );

  /// `combat_traveler_plate_steel_idle` — 11 px of contact, 30..40.
  static const SpriteFootprint combatTravelerPlateSteelIdle = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `combat_traveler_plate_steel_attack` — 11 px of contact, 33..43.
  static const SpriteFootprint combatTravelerPlateSteelAttack = SpriteFootprint(
    left: 33,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_plate_steel_hit` — 11 px of contact, 31..41.
  static const SpriteFootprint combatTravelerPlateSteelHit = SpriteFootprint(
    left: 31,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_plate_steel_stagger` — 10 px of contact, 28..37.
  static const SpriteFootprint combatTravelerPlateSteelStagger = SpriteFootprint(
    left: 28,
    right: 37,
    bottom: 61,
  );

  /// `combat_traveler_plate_steel_brace` — 10 px of contact, 29..38.
  static const SpriteFootprint combatTravelerPlateSteelBrace = SpriteFootprint(
    left: 29,
    right: 38,
    bottom: 62,
  );

  /// `combat_traveler_plate_unarmed_idle` — 11 px of contact, 30..40.
  static const SpriteFootprint combatTravelerPlateUnarmedIdle = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 62,
  );

  /// `combat_traveler_plate_unarmed_attack` — 12 px of contact, 30..41.
  static const SpriteFootprint combatTravelerPlateUnarmedAttack = SpriteFootprint(
    left: 30,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_plate_unarmed_hit` — 11 px of contact, 32..42.
  static const SpriteFootprint combatTravelerPlateUnarmedHit = SpriteFootprint(
    left: 32,
    right: 42,
    bottom: 62,
  );

  /// `combat_traveler_plate_unarmed_stagger` — 10 px of contact, 32..41.
  static const SpriteFootprint combatTravelerPlateUnarmedStagger = SpriteFootprint(
    left: 32,
    right: 41,
    bottom: 63,
  );

  /// `combat_traveler_plate_unarmed_brace` — 11 px of contact, 33..43.
  static const SpriteFootprint combatTravelerPlateUnarmedBrace = SpriteFootprint(
    left: 33,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_bronze_idle` — 10 px of contact, 30..39.
  static const SpriteFootprint combatTravelerJerkinBronzeIdle = SpriteFootprint(
    left: 30,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_bronze_attack` — 10 px of contact, 30..39.
  static const SpriteFootprint combatTravelerJerkinBronzeAttack = SpriteFootprint(
    left: 30,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_bronze_hit` — 10 px of contact, 34..43.
  static const SpriteFootprint combatTravelerJerkinBronzeHit = SpriteFootprint(
    left: 34,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_bronze_stagger` — 10 px of contact, 30..39.
  static const SpriteFootprint combatTravelerJerkinBronzeStagger = SpriteFootprint(
    left: 30,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_bronze_brace` — 10 px of contact, 30..39.
  static const SpriteFootprint combatTravelerJerkinBronzeBrace = SpriteFootprint(
    left: 30,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_steel_idle` — 12 px of contact, 30..41.
  static const SpriteFootprint combatTravelerJerkinSteelIdle = SpriteFootprint(
    left: 30,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_steel_attack` — 12 px of contact, 32..43.
  static const SpriteFootprint combatTravelerJerkinSteelAttack = SpriteFootprint(
    left: 32,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_steel_hit` — 12 px of contact, 35..46.
  static const SpriteFootprint combatTravelerJerkinSteelHit = SpriteFootprint(
    left: 35,
    right: 46,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_steel_stagger` — 11 px of contact, 30..40.
  static const SpriteFootprint combatTravelerJerkinSteelStagger = SpriteFootprint(
    left: 30,
    right: 40,
    bottom: 63,
  );

  /// `combat_traveler_jerkin_steel_brace` — 13 px of contact, 29..41.
  static const SpriteFootprint combatTravelerJerkinSteelBrace = SpriteFootprint(
    left: 29,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_unarmed_idle` — 11 px of contact, 28..38.
  static const SpriteFootprint combatTravelerJerkinUnarmedIdle = SpriteFootprint(
    left: 28,
    right: 38,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_unarmed_attack` — 11 px of contact, 25..35.
  static const SpriteFootprint combatTravelerJerkinUnarmedAttack = SpriteFootprint(
    left: 25,
    right: 35,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_unarmed_hit` — 11 px of contact, 29..39.
  static const SpriteFootprint combatTravelerJerkinUnarmedHit = SpriteFootprint(
    left: 29,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_unarmed_stagger` — 11 px of contact, 29..39.
  static const SpriteFootprint combatTravelerJerkinUnarmedStagger = SpriteFootprint(
    left: 29,
    right: 39,
    bottom: 63,
  );

  /// `combat_traveler_jerkin_unarmed_brace` — 11 px of contact, 29..39.
  static const SpriteFootprint combatTravelerJerkinUnarmedBrace = SpriteFootprint(
    left: 29,
    right: 39,
    bottom: 62,
  );

  /// `combat_traveler_coat_bronze_idle` — 12 px of contact, 30..41.
  static const SpriteFootprint combatTravelerCoatBronzeIdle = SpriteFootprint(
    left: 30,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_coat_bronze_attack` — 12 px of contact, 32..43.
  static const SpriteFootprint combatTravelerCoatBronzeAttack = SpriteFootprint(
    left: 32,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_coat_bronze_hit` — 12 px of contact, 35..46.
  static const SpriteFootprint combatTravelerCoatBronzeHit = SpriteFootprint(
    left: 35,
    right: 46,
    bottom: 62,
  );

  /// `combat_traveler_coat_bronze_stagger` — 12 px of contact, 34..45.
  static const SpriteFootprint combatTravelerCoatBronzeStagger = SpriteFootprint(
    left: 34,
    right: 45,
    bottom: 63,
  );

  /// `combat_traveler_coat_bronze_brace` — 12 px of contact, 33..44.
  static const SpriteFootprint combatTravelerCoatBronzeBrace = SpriteFootprint(
    left: 33,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_coat_steel_idle` — 9 px of contact, 29..37.
  static const SpriteFootprint combatTravelerCoatSteelIdle = SpriteFootprint(
    left: 29,
    right: 37,
    bottom: 62,
  );

  /// `combat_traveler_coat_steel_attack` — 9 px of contact, 35..43.
  static const SpriteFootprint combatTravelerCoatSteelAttack = SpriteFootprint(
    left: 35,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_coat_steel_hit` — 9 px of contact, 34..42.
  static const SpriteFootprint combatTravelerCoatSteelHit = SpriteFootprint(
    left: 34,
    right: 42,
    bottom: 62,
  );

  /// `combat_traveler_coat_steel_stagger` — 8 px of contact, 37..44.
  static const SpriteFootprint combatTravelerCoatSteelStagger = SpriteFootprint(
    left: 37,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_coat_steel_brace` — 9 px of contact, 30..38.
  static const SpriteFootprint combatTravelerCoatSteelBrace = SpriteFootprint(
    left: 30,
    right: 38,
    bottom: 62,
  );

  /// `combat_traveler_coat_unarmed_idle` — 10 px of contact, 28..37.
  static const SpriteFootprint combatTravelerCoatUnarmedIdle = SpriteFootprint(
    left: 28,
    right: 37,
    bottom: 62,
  );

  /// `combat_traveler_coat_unarmed_attack` — 10 px of contact, 28..37.
  static const SpriteFootprint combatTravelerCoatUnarmedAttack = SpriteFootprint(
    left: 28,
    right: 37,
    bottom: 62,
  );

  /// `combat_traveler_coat_unarmed_hit` — 9 px of contact, 34..42.
  static const SpriteFootprint combatTravelerCoatUnarmedHit = SpriteFootprint(
    left: 34,
    right: 42,
    bottom: 63,
  );

  /// `combat_traveler_coat_unarmed_stagger` — 10 px of contact, 29..38.
  static const SpriteFootprint combatTravelerCoatUnarmedStagger = SpriteFootprint(
    left: 29,
    right: 38,
    bottom: 62,
  );

  /// `combat_traveler_coat_unarmed_brace` — 10 px of contact, 31..40.
  static const SpriteFootprint combatTravelerCoatUnarmedBrace = SpriteFootprint(
    left: 31,
    right: 40,
    bottom: 62,
  );

  /// `combat_traveler_base_steel_brace` — 12 px of contact, 37..48.
  static const SpriteFootprint combatTravelerBaseSteelBrace = SpriteFootprint(
    left: 37,
    right: 48,
    bottom: 62,
  );

  /// `combat_traveler_plate_longsword_idle` — 40 px of contact, 29..68.
  static const SpriteFootprint combatTravelerPlateLongswordIdle = SpriteFootprint(
    left: 29,
    right: 68,
    bottom: 62,
  );

  /// `combat_traveler_plate_longsword_attack` — 41 px of contact, 27..67.
  static const SpriteFootprint combatTravelerPlateLongswordAttack = SpriteFootprint(
    left: 27,
    right: 67,
    bottom: 62,
  );

  /// `combat_traveler_plate_longsword_hit` — 40 px of contact, 30..69.
  static const SpriteFootprint combatTravelerPlateLongswordHit = SpriteFootprint(
    left: 30,
    right: 69,
    bottom: 62,
  );

  /// `combat_traveler_plate_longsword_stagger` — 41 px of contact, 25..65.
  static const SpriteFootprint combatTravelerPlateLongswordStagger = SpriteFootprint(
    left: 25,
    right: 65,
    bottom: 63,
  );

  /// `combat_traveler_plate_longsword_brace` — 41 px of contact, 24..64.
  static const SpriteFootprint combatTravelerPlateLongswordBrace = SpriteFootprint(
    left: 24,
    right: 64,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_longsword_idle` — 41 px of contact, 26..66.
  static const SpriteFootprint combatTravelerJerkinLongswordIdle = SpriteFootprint(
    left: 26,
    right: 66,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_longsword_attack` — 42 px of contact, 29..70.
  static const SpriteFootprint combatTravelerJerkinLongswordAttack = SpriteFootprint(
    left: 29,
    right: 70,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_longsword_hit` — 39 px of contact, 29..67.
  static const SpriteFootprint combatTravelerJerkinLongswordHit = SpriteFootprint(
    left: 29,
    right: 67,
    bottom: 62,
  );

  /// `combat_traveler_jerkin_longsword_stagger` — 39 px of contact, 28..66.
  static const SpriteFootprint combatTravelerJerkinLongswordStagger = SpriteFootprint(
    left: 28,
    right: 66,
    bottom: 63,
  );

  /// `combat_traveler_jerkin_longsword_brace` — 40 px of contact, 33..72.
  static const SpriteFootprint combatTravelerJerkinLongswordBrace = SpriteFootprint(
    left: 33,
    right: 72,
    bottom: 62,
  );

  /// `combat_traveler_coat_longsword_idle` — 40 px of contact, 21..60.
  static const SpriteFootprint combatTravelerCoatLongswordIdle = SpriteFootprint(
    left: 21,
    right: 60,
    bottom: 62,
  );

  /// `combat_traveler_coat_longsword_attack` — 41 px of contact, 29..69.
  static const SpriteFootprint combatTravelerCoatLongswordAttack = SpriteFootprint(
    left: 29,
    right: 69,
    bottom: 62,
  );

  /// `combat_traveler_coat_longsword_hit` — 41 px of contact, 30..70.
  static const SpriteFootprint combatTravelerCoatLongswordHit = SpriteFootprint(
    left: 30,
    right: 70,
    bottom: 63,
  );

  /// `combat_traveler_coat_longsword_stagger` — 42 px of contact, 28..69.
  static const SpriteFootprint combatTravelerCoatLongswordStagger = SpriteFootprint(
    left: 28,
    right: 69,
    bottom: 62,
  );

  /// `combat_traveler_coat_longsword_brace` — 39 px of contact, 25..63.
  static const SpriteFootprint combatTravelerCoatLongswordBrace = SpriteFootprint(
    left: 25,
    right: 63,
    bottom: 62,
  );

  /// `combat_traveler_base_longsword_idle` — 40 px of contact, 48..87.
  static const SpriteFootprint combatTravelerBaseLongswordIdle = SpriteFootprint(
    left: 48,
    right: 87,
    bottom: 62,
  );

  /// `combat_traveler_base_longsword_attack` — 11 px of contact, 49..59.
  static const SpriteFootprint combatTravelerBaseLongswordAttack = SpriteFootprint(
    left: 49,
    right: 59,
    bottom: 63,
  );

  /// `combat_traveler_base_longsword_hit` — 43 px of contact, 45..87.
  static const SpriteFootprint combatTravelerBaseLongswordHit = SpriteFootprint(
    left: 45,
    right: 87,
    bottom: 62,
  );

  /// `combat_traveler_base_longsword_stagger` — 41 px of contact, 43..83.
  static const SpriteFootprint combatTravelerBaseLongswordStagger = SpriteFootprint(
    left: 43,
    right: 83,
    bottom: 62,
  );

  /// `combat_traveler_base_longsword_brace` — 43 px of contact, 49..91.
  static const SpriteFootprint combatTravelerBaseLongswordBrace = SpriteFootprint(
    left: 49,
    right: 91,
    bottom: 62,
  );

  /// `combat_traveler_warden_unarmed_idle` — 11 px of contact, 37..47.
  static const SpriteFootprint combatTravelerWardenUnarmedIdle = SpriteFootprint(
    left: 37,
    right: 47,
    bottom: 62,
  );

  /// `combat_traveler_warden_unarmed_attack` — 11 px of contact, 33..43.
  static const SpriteFootprint combatTravelerWardenUnarmedAttack = SpriteFootprint(
    left: 33,
    right: 43,
    bottom: 62,
  );

  /// `combat_traveler_warden_unarmed_hit` — 11 px of contact, 38..48.
  static const SpriteFootprint combatTravelerWardenUnarmedHit = SpriteFootprint(
    left: 38,
    right: 48,
    bottom: 62,
  );

  /// `combat_traveler_warden_unarmed_stagger` — 11 px of contact, 37..47.
  static const SpriteFootprint combatTravelerWardenUnarmedStagger = SpriteFootprint(
    left: 37,
    right: 47,
    bottom: 63,
  );

  /// `combat_traveler_warden_unarmed_brace` — 11 px of contact, 35..45.
  static const SpriteFootprint combatTravelerWardenUnarmedBrace = SpriteFootprint(
    left: 35,
    right: 45,
    bottom: 62,
  );

  /// `combat_traveler_warden_steel_idle` — 11 px of contact, 34..44.
  static const SpriteFootprint combatTravelerWardenSteelIdle = SpriteFootprint(
    left: 34,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_steel_attack` — 11 px of contact, 36..46.
  static const SpriteFootprint combatTravelerWardenSteelAttack = SpriteFootprint(
    left: 36,
    right: 46,
    bottom: 62,
  );

  /// `combat_traveler_warden_steel_hit` — 17 px of contact, 28..44.
  static const SpriteFootprint combatTravelerWardenSteelHit = SpriteFootprint(
    left: 28,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_steel_stagger` — 11 px of contact, 36..46.
  static const SpriteFootprint combatTravelerWardenSteelStagger = SpriteFootprint(
    left: 36,
    right: 46,
    bottom: 62,
  );

  /// `combat_traveler_warden_steel_brace` — 11 px of contact, 34..44.
  static const SpriteFootprint combatTravelerWardenSteelBrace = SpriteFootprint(
    left: 34,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_bronze_idle` — 11 px of contact, 34..44.
  static const SpriteFootprint combatTravelerWardenBronzeIdle = SpriteFootprint(
    left: 34,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_bronze_attack` — 16 px of contact, 27..42.
  static const SpriteFootprint combatTravelerWardenBronzeAttack = SpriteFootprint(
    left: 27,
    right: 42,
    bottom: 62,
  );

  /// `combat_traveler_warden_bronze_hit` — 11 px of contact, 34..44.
  static const SpriteFootprint combatTravelerWardenBronzeHit = SpriteFootprint(
    left: 34,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_bronze_stagger` — 9 px of contact, 33..41.
  static const SpriteFootprint combatTravelerWardenBronzeStagger = SpriteFootprint(
    left: 33,
    right: 41,
    bottom: 62,
  );

  /// `combat_traveler_warden_bronze_brace` — 11 px of contact, 34..44.
  static const SpriteFootprint combatTravelerWardenBronzeBrace = SpriteFootprint(
    left: 34,
    right: 44,
    bottom: 62,
  );

  /// `combat_traveler_warden_longsword_idle` — 43 px of contact, 46..88.
  static const SpriteFootprint combatTravelerWardenLongswordIdle = SpriteFootprint(
    left: 46,
    right: 88,
    bottom: 62,
  );

  /// `combat_traveler_warden_longsword_attack` — 40 px of contact, 45..84.
  static const SpriteFootprint combatTravelerWardenLongswordAttack = SpriteFootprint(
    left: 45,
    right: 84,
    bottom: 63,
  );

  /// `combat_traveler_warden_longsword_hit` — 40 px of contact, 46..85.
  static const SpriteFootprint combatTravelerWardenLongswordHit = SpriteFootprint(
    left: 46,
    right: 85,
    bottom: 62,
  );

  /// `combat_traveler_warden_longsword_stagger` — 42 px of contact, 41..82.
  static const SpriteFootprint combatTravelerWardenLongswordStagger = SpriteFootprint(
    left: 41,
    right: 82,
    bottom: 62,
  );

  /// `combat_traveler_warden_longsword_brace` — 11 px of contact, 42..52.
  static const SpriteFootprint combatTravelerWardenLongswordBrace = SpriteFootprint(
    left: 42,
    right: 52,
    bottom: 62,
  );

  /// Every gather-scene subject plate, keyed by the asset path the scene
  /// resolves.
  ///
  /// A map rather than named constants because the consumer is
  /// `AmbientStage._prop`, which is handed a `StageScenery` and knows only its
  /// `assetPath`. Hand-wiring a footprint into each of the twenty-odd
  /// `StageScenery` literals would put the measurement and the plate in two
  /// places that can disagree; this cannot drift, because both sides come from
  /// the same packaging run.
  static const Map<String, SpriteFootprint> byNodeAsset =
      <String, SpriteFootprint>{
    'assets/art/v1/node/collapsed_span.png': SpriteFootprint(
      left: 15,
      right: 33,
      bottom: 90,
    ),
    'assets/art/v1/node/copper_seam.png': SpriteFootprint(
      left: 15,
      right: 33,
      bottom: 90,
    ),
    'assets/art/v1/node/deep_hollow_thicket.png': SpriteFootprint(
      left: 34,
      right: 79,
      bottom: 93,
    ),
    'assets/art/v1/node/deep_tin_seam.png': SpriteFootprint(
      left: 22,
      right: 80,
      bottom: 90,
    ),
    'assets/art/v1/node/duskcap_grove.png': SpriteFootprint(
      left: 28,
      right: 60,
      bottom: 78,
    ),
    'assets/art/v1/node/frostpine_stand.png': SpriteFootprint(
      left: 18,
      right: 78,
      bottom: 87,
    ),
    'assets/art/v1/node/gallery_tin_lode.png': SpriteFootprint(
      left: 22,
      right: 80,
      bottom: 90,
    ),
    'assets/art/v1/node/hardened_copper_seam.png': SpriteFootprint(
      left: 15,
      right: 33,
      bottom: 90,
    ),
    'assets/art/v1/node/heartwood_oak.png': SpriteFootprint(
      left: 35,
      right: 71,
      bottom: 94,
    ),
    'assets/art/v1/node/hollow_thicket.png': SpriteFootprint(
      left: 34,
      right: 79,
      bottom: 93,
    ),
    'assets/art/v1/node/meadow_patch.png': SpriteFootprint(
      left: 33,
      right: 74,
      bottom: 85,
    ),
    'assets/art/v1/node/mill_garden.png': SpriteFootprint(
      left: 33,
      right: 74,
      bottom: 85,
    ),
    'assets/art/v1/node/oak_stand.png': SpriteFootprint(
      left: 35,
      right: 71,
      bottom: 94,
    ),
    'assets/art/v1/node/old_workings.png': SpriteFootprint(
      left: 15,
      right: 33,
      bottom: 90,
    ),
    'assets/art/v1/node/oldgrowth_frostpine.png': SpriteFootprint(
      left: 18,
      right: 78,
      bottom: 87,
    ),
    'assets/art/v1/node/rimefrost_hollow.png': SpriteFootprint(
      left: 3,
      right: 93,
      bottom: 91,
    ),
    'assets/art/v1/node/sheltered_frost_meadow.png': SpriteFootprint(
      left: 3,
      right: 93,
      bottom: 91,
    ),
    'assets/art/v1/node/silkstrand_thicket.png': SpriteFootprint(
      left: 34,
      right: 79,
      bottom: 93,
    ),
    'assets/art/v1/node/station_cookfire.png': SpriteFootprint(
      left: 7,
      right: 56,
      bottom: 60,
    ),
    'assets/art/v1/node/station_forge.png': SpriteFootprint(
      left: 24,
      right: 39,
      bottom: 61,
    ),
    'assets/art/v1/node/tin_seam.png': SpriteFootprint(
      left: 22,
      right: 80,
      bottom: 90,
    ),
    'assets/art/v1/node/undercroft_silkfall.png': SpriteFootprint(
      left: 34,
      right: 79,
      bottom: 93,
    ),
    'assets/art/v1/node/veiled_silkstrand.png': SpriteFootprint(
      left: 34,
      right: 79,
      bottom: 93,
    ),
    'assets/art/v1/node/warded_grove.png': SpriteFootprint(
      left: 35,
      right: 71,
      bottom: 94,
    ),
    'assets/art/v1/work/prop_copper_face.png': SpriteFootprint(
      left: 0,
      right: 37,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_copper_seam.png': SpriteFootprint(
      left: 22,
      right: 82,
      bottom: 92,
    ),
    'assets/art/v1/work/prop_deep_tin_lode.png': SpriteFootprint(
      left: 1,
      right: 47,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_duskcap_bed.png': SpriteFootprint(
      left: 11,
      right: 33,
      bottom: 33,
    ),
    'assets/art/v1/work/prop_duskcap_grove.png': SpriteFootprint(
      left: 26,
      right: 47,
      bottom: 94,
    ),
    'assets/art/v1/work/prop_frostpine_cut.png': SpriteFootprint(
      left: 3,
      right: 44,
      bottom: 46,
    ),
    'assets/art/v1/work/prop_gloom_silk.png': SpriteFootprint(
      left: 0,
      right: 47,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_hardened_copper_face.png': SpriteFootprint(
      left: 0,
      right: 37,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_hardened_copper_seam.png': SpriteFootprint(
      left: 22,
      right: 67,
      bottom: 92,
    ),
    'assets/art/v1/work/prop_heartwood_oak_cut.png': SpriteFootprint(
      left: 0,
      right: 47,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_hollow_root.png': SpriteFootprint(
      left: 8,
      right: 38,
      bottom: 45,
    ),
    'assets/art/v1/work/prop_meadow_bed.png': SpriteFootprint(
      left: 11,
      right: 35,
      bottom: 38,
    ),
    'assets/art/v1/work/prop_meadow_patch.png': SpriteFootprint(
      left: 49,
      right: 74,
      bottom: 91,
    ),
    'assets/art/v1/work/prop_oak_cut.png': SpriteFootprint(
      left: 9,
      right: 39,
      bottom: 41,
    ),
    'assets/art/v1/work/prop_oak_stand.png': SpriteFootprint(
      left: 15,
      right: 85,
      bottom: 90,
    ),
    'assets/art/v1/work/prop_oldgrowth_frostpine_cut.png': SpriteFootprint(
      left: 1,
      right: 46,
      bottom: 43,
    ),
    'assets/art/v1/work/prop_rime_cushion.png': SpriteFootprint(
      left: 6,
      right: 41,
      bottom: 43,
    ),
    'assets/art/v1/work/prop_ruin_face.png': SpriteFootprint(
      left: 16,
      right: 34,
      bottom: 46,
    ),
    'assets/art/v1/work/prop_tin_face.png': SpriteFootprint(
      left: 0,
      right: 47,
      bottom: 47,
    ),
    'assets/art/v1/work/prop_tin_seam.png': SpriteFootprint(
      left: 22,
      right: 67,
      bottom: 91,
    ),
  };
}
