// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Why a read returned no record.
///
/// The whole safety argument rests on this enum having more than two cases.
/// "Absent" and "I could not tell" must never collapse into one value: a
/// locked-device read that reports absence is how a replacement identity gets
/// minted over a live save.
enum PlatformSecureReadStatus {
  /// A record exists and is in the result.
  found,
  /// The keychain was readable and holds no record for this app.
  ///
  /// Only ever produced by `errSecItemNotFound`. Nothing else may map here.
  absent,
  /// The keychain could not answer. **Not absence.**
  ///
  /// Chiefly `errSecInteractionNotAllowed`, which is what a read gets before
  /// the first unlock since boot. Callers must treat this as an I/O fault and
  /// refuse, never as a new installation.
  unavailable,
}

/// Why a create failed.
enum PlatformSecureWriteStatus {
  created,
  /// An item was already there. **Never overwritten.**
  ///
  /// The platform call is `SecItemAdd` and there is deliberately no update
  /// path: an identity that already exists is either the live one or evidence
  /// of a crash between minting and the first commit, and both are cases where
  /// replacing it would orphan a save.
  alreadyExists,
  /// The keychain refused for any other reason.
  failed,
}

/// The identity as it is stored on the device.
class PlatformIdentityRecord {
  PlatformIdentityRecord({
    required this.saveId,
    required this.salt,
  });

  /// Opaque lineage id, minted by the app at new-game time.
  String saveId;

  /// The raw pseudonymization salt. Protected local reconciliation metadata:
  /// it reaches `OriginPseudonymizer` and nothing else.
  Uint8List salt;

  List<Object?> _toList() {
    return <Object?>[
      saveId,
      salt,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformIdentityRecord decode(Object result) {
    result as List<Object?>;
    return PlatformIdentityRecord(
      saveId: result[0]! as String,
      salt: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformIdentityRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(saveId, other.saveId) && _deepEquals(salt, other.salt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformIdentityRecord(saveId: $saveId, salt: $salt)';
  }
}

class PlatformSecureReadResult {
  PlatformSecureReadResult({
    required this.status,
    this.record,
    this.osStatus,
  });

  PlatformSecureReadStatus status;

  /// Non-null exactly when [status] is `found`.
  PlatformIdentityRecord? record;

  /// The raw `OSStatus`, for a log line. Never shown to a player and never
  /// used to make a decision — the decision is [status].
  int? osStatus;

  List<Object?> _toList() {
    return <Object?>[
      status,
      record,
      osStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformSecureReadResult decode(Object result) {
    result as List<Object?>;
    return PlatformSecureReadResult(
      status: result[0]! as PlatformSecureReadStatus,
      record: result[1] as PlatformIdentityRecord?,
      osStatus: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSecureReadResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(record, other.record) && _deepEquals(osStatus, other.osStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSecureReadResult(status: $status, record: $record, osStatus: $osStatus)';
  }
}

/// The result of applying `NSURLIsExcludedFromBackupKey`.
///
/// Reported per path rather than as one boolean, because a partial application
/// is the interesting case: a directory that is excluded while one file inside
/// it is not is still a ledger that travels.
class PlatformBackupExclusionReport {
  PlatformBackupExclusionReport({
    required this.excluded,
    required this.missing,
    required this.failed,
  });

  /// Paths that now carry the exclusion, verified by reading the attribute
  /// back rather than by the setter returning without error.
  List<String> excluded;

  /// Paths that do not exist yet. Not a failure: `StorageLayout` names every
  /// file it *may* create, and the journal sidecar usually does not exist.
  List<String> missing;

  /// Paths that exist and could not be excluded. Each entry is
  /// `path\t<reason>`. This is the one condition that means the ledger would
  /// travel.
  List<String> failed;

  List<Object?> _toList() {
    return <Object?>[
      excluded,
      missing,
      failed,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformBackupExclusionReport decode(Object result) {
    result as List<Object?>;
    return PlatformBackupExclusionReport(
      excluded: (result[0]! as List<Object?>).cast<String>(),
      missing: (result[1]! as List<Object?>).cast<String>(),
      failed: (result[2]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformBackupExclusionReport || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(excluded, other.excluded) && _deepEquals(missing, other.missing) && _deepEquals(failed, other.failed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformBackupExclusionReport(excluded: $excluded, missing: $missing, failed: $failed)';
  }
}

/// Read-back of what was actually configured, for tests and for a startup
/// self-check.
///
/// Exists because "we set the attribute" and "the attribute is set" are
/// different claims, and only the second one is worth anything after a
/// directory has been recreated by a restore.
class PlatformSecureStoreDiagnostics {
  PlatformSecureStoreDiagnostics({
    this.keychainAccessibility,
    required this.excludedPaths,
    required this.notExcludedPaths,
    required this.missingPaths,
  });

  /// The `kSecAttrAccessible` value on the stored item, as its raw string
  /// (`cku` for AfterFirstUnlockThisDeviceOnly, `ak` for WhenUnlocked, and so
  /// on). Null when no item is stored.
  ///
  /// A string rather than an enum because the assertion worth making is
  /// "exactly the constant we asked for", and an enum would silently fold an
  /// unexpected value into a known case.
  String? keychainAccessibility;

  List<String> excludedPaths;

  List<String> notExcludedPaths;

  List<String> missingPaths;

  List<Object?> _toList() {
    return <Object?>[
      keychainAccessibility,
      excludedPaths,
      notExcludedPaths,
      missingPaths,
    ];
  }

  Object encode() {
    return _toList();  }

  static PlatformSecureStoreDiagnostics decode(Object result) {
    result as List<Object?>;
    return PlatformSecureStoreDiagnostics(
      keychainAccessibility: result[0] as String?,
      excludedPaths: (result[1]! as List<Object?>).cast<String>(),
      notExcludedPaths: (result[2]! as List<Object?>).cast<String>(),
      missingPaths: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSecureStoreDiagnostics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keychainAccessibility, other.keychainAccessibility) && _deepEquals(excludedPaths, other.excludedPaths) && _deepEquals(notExcludedPaths, other.notExcludedPaths) && _deepEquals(missingPaths, other.missingPaths);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformSecureStoreDiagnostics(keychainAccessibility: $keychainAccessibility, excludedPaths: $excludedPaths, notExcludedPaths: $notExcludedPaths, missingPaths: $missingPaths)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformSecureReadStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformSecureWriteStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformIdentityRecord) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformSecureReadResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformBackupExclusionReport) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformSecureStoreDiagnostics) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformSecureReadStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformSecureWriteStatus.values[value];
      case 131:
        return PlatformIdentityRecord.decode(readValue(buffer)!);
      case 132:
        return PlatformSecureReadResult.decode(readValue(buffer)!);
      case 133:
        return PlatformBackupExclusionReport.decode(readValue(buffer)!);
      case 134:
        return PlatformSecureStoreDiagnostics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SecureStoreHostApi {
  /// Constructor for [SecureStoreHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SecureStoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Reads the stored identity.
  ///
  /// Never throws for absence — absence is a typed status. It throws only when
  /// the platform itself misbehaves in a way that has no status.
  Future<PlatformSecureReadResult> readIdentity() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.readIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformSecureReadResult;
  }

  /// Creates the identity. **Add-only.**
  ///
  /// There is no update method on this interface, and that is the enforcement
  /// mechanism for "never overwrite an existing key because a read failed": a
  /// caller that has just had a read fail cannot express an overwrite.
  Future<PlatformSecureWriteStatus> createIdentity(PlatformIdentityRecord record) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.createIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[record]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformSecureWriteStatus;
  }

  /// Removes the identity. Full reset only, and only from an explicit player
  /// action.
  Future<bool> deleteIdentity() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.deleteIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Applies `NSURLIsExcludedFromBackupKey` to [directoryPath] and each of
  /// [filePaths], and verifies each by reading the attribute back.
  ///
  /// **Must be called on every launch.** The attribute lives on the filesystem
  /// node, not on the app: if the directory is deleted and recreated — by a
  /// restore, by a reinstall, by our own `ensureExists` after a wipe — the
  /// exclusion is gone and nothing reports it.
  Future<PlatformBackupExclusionReport> applyBackupExclusions(String directoryPath, List<String> filePaths) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.applyBackupExclusions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[directoryPath, filePaths]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformBackupExclusionReport;
  }

  /// Re-applies `NSURLIsExcludedFromBackupKey` to [paths] and nothing else.
  ///
  /// **Why a second, narrower method.** Apple documents
  /// `NSURLIsExcludedFromBackupKey` as a resource value on the filesystem node,
  /// and resource values do not follow a path: a replacement, an atomic write,
  /// a rename over the top, or a delete-and-recreate all leave the path
  /// pointing at a *different* node, which carries whatever attributes it was
  /// born with — none.
  ///
  /// The save layout does all of those. `FileLedgerJournal.replaceLines` writes
  /// a sidecar and renames it over the journal, so after every compaction the
  /// journal path names a node that has never been excluded. The snapshot slots
  /// are created on their first write. So a once-at-launch application is
  /// correct until the first commit and silently wrong after it.
  ///
  /// Separate from [applyBackupExclusions] because that one is the launch
  /// sweep: it takes the directory as well, and reports the whole layout. This
  /// is the per-write call — a list of the paths a single operation just
  /// touched, no directory, so it stays cheap enough to sit on the commit path.
  /// Two `setResourceValues` round trips per file, against an fsync.
  ///
  /// Idempotent. Paths that do not exist come back as `missing`, not `failed`.
  Future<PlatformBackupExclusionReport> reapplyBackupExclusions(List<String> paths) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.reapplyBackupExclusions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[paths]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformBackupExclusionReport;
  }

  /// Reads back what is actually configured. Diagnostics only.
  Future<PlatformSecureStoreDiagnostics> readDiagnostics(List<String> paths) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.readDiagnostics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[paths]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PlatformSecureStoreDiagnostics;
  }
}
