// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors `StepAuthorization` in stride_core.
enum PlatformAuthorization { granted, denied, unavailable }

/// Mirrors `CursorStatus` in stride_core.
enum PlatformCursorStatus { valid, invalidated }

/// An authoritative re-read of a bounded window, sent only when the cursor was
/// invalidated. See `StepRescan` in stride_core for the recovery strategy.
class PlatformRescan {
  PlatformRescan({
    required this.windowStartMillis,
    required this.windowEndMillis,
    required this.windowTotal,
    required this.truncated,
  });

  /// Start of the rescanned window — the watermark the caller supplied,
  /// clamped by the adapter to its maximum window.
  int windowStartMillis;

  int windowEndMillis;

  /// The authoritative total for the window. A total, not a delta: after cursor
  /// loss only an absolute figure can be reconciled against what was already
  /// granted.
  int windowTotal;

  /// True when the window was clamped, leaving an unreachable gap. Those steps
  /// are recorded, never granted — inventing progress is worse than missing it.
  bool truncated;

  List<Object?> _toList() {
    return <Object?>[
      windowStartMillis,
      windowEndMillis,
      windowTotal,
      truncated,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformRescan decode(Object result) {
    result as List<Object?>;
    return PlatformRescan(
      windowStartMillis: result[0]! as int,
      windowEndMillis: result[1]! as int,
      windowTotal: result[2]! as int,
      truncated: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformRescan || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(windowStartMillis, other.windowStartMillis) &&
        _deepEquals(windowEndMillis, other.windowEndMillis) &&
        _deepEquals(windowTotal, other.windowTotal) &&
        _deepEquals(truncated, other.truncated);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformRescan(windowStartMillis: $windowStartMillis, windowEndMillis: $windowEndMillis, windowTotal: $windowTotal, truncated: $truncated)';
  }
}

class PlatformFetchResult {
  PlatformFetchResult({
    required this.status,
    required this.newSteps,
    required this.deletedSteps,
    this.cursor,
    this.rescan,
  });

  PlatformCursorStatus status;

  /// A true delta only when [status] is `valid`. Meaningless otherwise.
  int newSteps;

  /// Steps removed by corrections since the cursor. Information, not an
  /// instruction — reconciliation never revokes granted progress.
  int deletedSteps;

  /// Opaque. An archived HKQueryAnchor on iOS, a changes token on Android.
  /// The caller stores and returns it without inspecting it, and persists it
  /// only after the resulting batch is committed to the ledger.
  Uint8List? cursor;

  PlatformRescan? rescan;

  List<Object?> _toList() {
    return <Object?>[status, newSteps, deletedSteps, cursor, rescan];
  }

  Object encode() {
    return _toList();
  }

  static PlatformFetchResult decode(Object result) {
    result as List<Object?>;
    return PlatformFetchResult(
      status: result[0]! as PlatformCursorStatus,
      newSteps: result[1]! as int,
      deletedSteps: result[2]! as int,
      cursor: result[3] as Uint8List?,
      rescan: result[4] as PlatformRescan?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformFetchResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) &&
        _deepEquals(newSteps, other.newSteps) &&
        _deepEquals(deletedSteps, other.deletedSteps) &&
        _deepEquals(cursor, other.cursor) &&
        _deepEquals(rescan, other.rescan);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformFetchResult(status: $status, newSteps: $newSteps, deletedSteps: $deletedSteps, cursor: $cursor, rescan: $rescan)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformAuthorization) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformCursorStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformRescan) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PlatformFetchResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformAuthorization.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformCursorStatus.values[value];
      case 131:
        return PlatformRescan.decode(readValue(buffer)!);
      case 132:
        return PlatformFetchResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HealthHostApi {
  /// Constructor for [HealthHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HealthHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Whether the platform's health service is present and usable. False on
  /// Android without Health Connect installed — a normal state, not an error.
  Future<bool> isAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stride_health.HealthHostApi.isAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<PlatformAuthorization> requestAuthorization() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stride_health.HealthHostApi.requestAuthorization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformAuthorization;
  }

  /// Fetch steps since [cursor]. [watermarkMillis] bounds the rescan window if
  /// the cursor turns out to be invalid.
  Future<PlatformFetchResult> fetchNewSteps(
    Uint8List? cursor,
    int? watermarkMillis,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.stride_health.HealthHostApi.fetchNewSteps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cursor, watermarkMillis],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PlatformFetchResult;
  }
}
