/// The boundary where a platform's source identity becomes a pseudonym.
///
/// HealthKit hands us `HKSource.name` — which is a device name, which a player
/// may have called anything at all, and which the owner's privacy ruling
/// explicitly forbids persisting. Health Connect hands us a package name and a
/// device identifier. **None of those may cross into `stride_core`.**
///
/// This is the only place a raw platform identifier exists in Dart, and it
/// exists here for exactly as long as one call takes.
///
/// The core cannot enforce this by inspection — a `String` is a `String`. It
/// enforces it by *type*: `StepOriginKey` accepts only sixteen lowercase hex
/// characters, so a device name is not a representable value and this class is
/// the only thing that can produce one.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:stride_core/stride_core.dart';

/// Turns a raw platform source identifier into a stable pseudonymous key.
///
/// Keyed, not a bare hash. An unkeyed digest of a package name is trivially
/// reversible by anyone with a list of package names — which is everyone — so
/// it would be a pseudonym in name only.
final class OriginPseudonymizer {
  const OriginPseudonymizer(this._key);

  /// The app-local salt.
  ///
  /// **Protected local reconciliation metadata**, not a secret in the
  /// cryptographic sense. Its job is to make the mapping meaningless outside
  /// this installation, not to withstand an attacker who already has the
  /// device.
  final Uint8List _key;

  /// Builds a pseudonymizer from a stored salt.
  ///
  /// The salt is generated by the app at first run — the core cannot make one,
  /// having neither a clock nor randomness — and stored alongside the save.
  factory OriginPseudonymizer.fromSalt(String base64Salt) =>
      OriginPseudonymizer(base64Decode(base64Salt));

  /// Maps a raw platform identifier to its key.
  ///
  /// Deterministic: the same identifier and salt always give the same key, or
  /// a device would look new on every sync and its whole history would be
  /// re-granted.
  StepOriginKey pseudonymize(String rawPlatformIdentifier) {
    if (rawPlatformIdentifier.isEmpty) return StepOriginKey.unknown;

    final List<int> message = <int>[
      ..._key,
      0x1F, // separator, so key||message cannot collide with key'||message'
      ...utf8.encode(rawPlatformIdentifier),
    ];

    // FNV-1a, 64-bit. Not a cryptographic hash, and deliberately so: the
    // threat is casual identifiability of a device name inside a local save,
    // not a motivated attacker who already has the device and could read the
    // salt beside it. A dependency on package:crypto to defend against an
    // adversary who has already won is the wrong trade — the same reasoning
    // that chose CRC-32C for save integrity.
    return StepOriginKey(_hex64(_fnv1a(message)));
  }
}

int _fnv1a(List<int> message) {
  int hash = 0xcbf29ce484222325;
  for (final int byte in message) {
    hash ^= byte;
    hash = (hash * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF;
  }
  return hash;
}

/// Sixteen lowercase hex characters, unsigned.
///
/// Dart's `int` is 64-bit **signed**, so half of all hash values are negative
/// and `toRadixString(16)` renders them with a leading `-` — seventeen
/// characters, which `StepOriginKey` then refuses. Formatting the halves
/// separately with an unsigned shift is the fix.
///
/// Found by `different identifiers give different keys`, which is the shape of
/// test worth keeping: it did not assert the hash, it asserted the property the
/// hash exists to provide.
String _hex64(int value) {
  final int high = (value >>> 32) & 0xFFFFFFFF;
  final int low = value & 0xFFFFFFFF;
  return high.toRadixString(16).padLeft(8, '0') +
      low.toRadixString(16).padLeft(8, '0');
}

/// What happens when the salt is lost or changed.
///
/// Every origin re-keys, so every device the ledger knows about looks new and
/// every device it *did* know about looks abandoned. Concretely:
///
/// - Newly-keyed origins have no `grantedSlices`, so their recent buckets look
///   ungranted. Within the retention window, **that window would be granted a
///   second time.** This is the one way the design can double-count.
/// - The old origins' slices age out and compact normally. No credit is lost;
///   `totalGranted` and `grantedBeforeWatermark` are origin-independent.
///
/// So a lost salt is a **double-grant** risk, not a lost-grant risk, and it is
/// bounded by the retention window rather than unbounded.
///
/// **The rule: a save whose salt cannot be matched fails closed.** The save
/// records a fingerprint of the salt that produced its origin keys; a load that
/// cannot reproduce it refuses with [LoadRefusal.originKeyReset] rather than
/// guessing. Refusing is recoverable — the player can be offered a health
/// reconnect, which clears health state and keeps their earned progress. A
/// silent double-grant is not recoverable, because nothing detects it.
///
/// The salt is therefore stored beside the save and covered by the same backup
/// exclusions. It is never derived from a device identifier, which would make
/// it a device identifier.
// OriginSaltPolicy now lives in stride_core, because stride_storage needs it
// too and must not depend on this package -- stride_health pulls in Flutter,
// and the storage layer is deliberately pure dart:io so it can be tested by
//  with no emulator.
//
// Re-exported from stride_core via this package's barrel; the documentation of
// what salt loss costs stays here, with the code that mints it.
