/// The **reference implementation** of origin keying.
///
/// ===========================================================================
/// This is no longer the production path
/// ===========================================================================
///
/// Keying happens in Swift and Kotlin now, before the value crosses Pigeon
/// (owner ruling — see `origin_gateway.dart` for the trade and its cost). A raw
/// platform identifier does not reach Dart at all, so nothing in the shipping
/// Dart path calls this class.
///
/// It is kept, and kept exact, for the job that replaced its old one: **it is
/// the specification the two native implementations must match.** Two native
/// implementations are two chances to diverge, and a divergence is silent — a
/// re-keyed origin looks exactly like a new device, its recent buckets look
/// ungranted, and the retention window is granted a second time. Nothing
/// detects that.
///
/// So this file is the definition, `origin_key_vectors.dart` is the fixture
/// generated from it, and the Swift and Kotlin suites assert against those
/// vectors. A native adapter that disagrees with this function fails its own
/// tests rather than a player's ledger.
///
/// The algorithm: FNV-1a, 64-bit, over `salt || 0x1F || utf8(identifier)`,
/// rendered big-endian. Keyed rather than a bare digest — an unkeyed hash of a
/// package name is trivially reversible by anyone with a list of package names,
/// which is everyone.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:stride_core/stride_core.dart';

/// Turns a raw platform source identifier into a stable pseudonymous key.
///
/// Keyed, not a bare hash. An unkeyed digest of a package name is trivially
/// reversible by anyone with a list of package names — which is everyone — so
/// it would be a pseudonym in name only.
final class OriginPseudonymizer {
  const OriginPseudonymizer(this._key);

  /// The app-local salt.
  ///
  /// **Protected local reconciliation metadata**, not a secret in the
  /// cryptographic sense. Its job is to make the mapping meaningless outside
  /// this installation, not to withstand an attacker who already has the
  /// device.
  final Uint8List _key;

  /// Builds a pseudonymizer from a stored salt.
  ///
  /// The salt is generated by the app at first run — the core cannot make one,
  /// having neither a clock nor randomness — and stored alongside the save.
  factory OriginPseudonymizer.fromSalt(String base64Salt) =>
      OriginPseudonymizer(base64Decode(base64Salt));

  /// Maps a raw platform identifier to its key.
  ///
  /// Deterministic: the same identifier and salt always give the same key, or
  /// a device would look new on every sync and its whole history would be
  /// re-granted.
  StepOriginKey pseudonymize(String rawPlatformIdentifier) {
    if (rawPlatformIdentifier.isEmpty) return StepOriginKey.unknown;
    return StepOriginKey(_hex64(_fnv1a(_message(rawPlatformIdentifier))));
  }

  /// The same value in the shape the platform boundary carries.
  ///
  /// Eight bytes, big-endian, most significant first — the byte order is part
  /// of the specification, not an implementation detail. Swift's `Int64` and
  /// Kotlin's `Long` are both signed and both tempting to shift arithmetically;
  /// a native implementation that got the order or the sign wrong would produce
  /// a stable, self-consistent, and completely different key on that platform.
  ///
  /// An empty identifier returns **zero bytes**, which is the wire's way of
  /// saying "no source reported" and becomes `StepOriginKey.unknown`. It is not
  /// eight zero bytes: those would be a legal, ordinary key that the hash could
  /// in principle produce.
  Uint8List keyBytes(String rawPlatformIdentifier) {
    if (rawPlatformIdentifier.isEmpty) return Uint8List(0);

    final int hash = _fnv1a(_message(rawPlatformIdentifier));
    final Uint8List bytes = Uint8List(8);
    for (int i = 0; i < 8; i++) {
      // Unsigned shift. Dart's int is 64-bit SIGNED, and an arithmetic shift
      // here sign-extends for half of all hash values — which is the same class
      // of bug that once made this function emit seventeen characters.
      bytes[i] = (hash >>> (56 - i * 8)) & 0xFF;
    }
    return bytes;
  }

  List<int> _message(String rawPlatformIdentifier) => <int>[
    ..._key,
    0x1F, // separator, so key||message cannot collide with key'||message'
    ...utf8.encode(rawPlatformIdentifier),
  ];
}

/// The keying scheme this file implements.
///
/// Sent to native on `installOriginKeying`. An adapter that does not implement
/// this version refuses with `PlatformOriginKeyingOutcome.unsupportedAlgorithm`
/// rather than falling back — a silent fallback produces keys nothing else on
/// the device agrees with.
const int originKeyingAlgorithmVersion = 1;

int _fnv1a(List<int> message) {
  int hash = 0xcbf29ce484222325;
  for (final int byte in message) {
    hash ^= byte;
    hash = (hash * 0x100000001b3) & 0xFFFFFFFFFFFFFFFF;
  }
  return hash;
}

/// Sixteen lowercase hex characters, unsigned.
///
/// Dart's `int` is 64-bit **signed**, so half of all hash values are negative
/// and `toRadixString(16)` renders them with a leading `-` — seventeen
/// characters, which `StepOriginKey` then refuses. Formatting the halves
/// separately with an unsigned shift is the fix.
///
/// Found by `different identifiers give different keys`, which is the shape of
/// test worth keeping: it did not assert the hash, it asserted the property the
/// hash exists to provide.
String _hex64(int value) {
  final int high = (value >>> 32) & 0xFFFFFFFF;
  final int low = value & 0xFFFFFFFF;
  return high.toRadixString(16).padLeft(8, '0') +
      low.toRadixString(16).padLeft(8, '0');
}

/// What happens when the salt is lost or changed.
///
/// Every origin re-keys, so every device the ledger knows about looks new and
/// every device it *did* know about looks abandoned. Concretely:
///
/// - Newly-keyed origins have no `grantedSlices`, so their recent buckets look
///   ungranted. Within the retention window, **that window would be granted a
///   second time.** This is the one way the design can double-count.
/// - The old origins' slices age out and compact normally. No credit is lost;
///   `totalGranted` and `grantedBeforeWatermark` are origin-independent.
///
/// So a lost salt is a **double-grant** risk, not a lost-grant risk, and it is
/// bounded by the retention window rather than unbounded.
///
/// **The rule: a save whose salt cannot be matched fails closed.** The save
/// records a fingerprint of the salt that produced its origin keys; a load that
/// cannot reproduce it refuses with [LoadRefusal.originKeyReset] rather than
/// guessing. Refusing is recoverable — the player can be offered a health
/// reconnect, which clears health state and keeps their earned progress. A
/// silent double-grant is not recoverable, because nothing detects it.
///
/// The salt is therefore stored beside the save and covered by the same backup
/// exclusions. It is never derived from a device identifier, which would make
/// it a device identifier.
// OriginSaltPolicy now lives in stride_core, because stride_storage needs it
// too and must not depend on this package -- stride_health pulls in Flutter,
// and the storage layer is deliberately pure dart:io so it can be tested by
//  with no emulator.
//
// Re-exported from stride_core via this package's barrel; the documentation of
// what salt loss costs stays here, with the code that mints it.
