// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Why a read returned no record.
///
/// The whole safety argument rests on this enum having more than two cases.
/// "Absent" and "I could not tell" must never collapse into one value: a
/// locked-device read that reports absence is how a replacement identity gets
/// minted over a live save.
enum PlatformSecureReadStatus: Int, CaseIterable {
  /// A record exists and is in the result.
  case found = 0
  /// The keychain was readable and holds no record for this app.
  ///
  /// Only ever produced by `errSecItemNotFound`. Nothing else may map here.
  case absent = 1
  /// The keychain could not answer. **Not absence.**
  ///
  /// Chiefly `errSecInteractionNotAllowed`, which is what a read gets before
  /// the first unlock since boot. Callers must treat this as an I/O fault and
  /// refuse, never as a new installation.
  case unavailable = 2
}

/// Why a create failed.
enum PlatformSecureWriteStatus: Int, CaseIterable {
  case created = 0
  /// An item was already there. **Never overwritten.**
  ///
  /// The platform call is `SecItemAdd` and there is deliberately no update
  /// path: an identity that already exists is either the live one or evidence
  /// of a crash between minting and the first commit, and both are cases where
  /// replacing it would orphan a save.
  case alreadyExists = 1
  /// The keychain refused for any other reason.
  case failed = 2
}

/// The identity as it is stored on the device.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformIdentityRecord: Hashable, CustomStringConvertible {
  /// Opaque lineage id, minted by the app at new-game time.
  var saveId: String
  /// The raw pseudonymization salt. Protected local reconciliation metadata:
  /// it reaches `OriginPseudonymizer` and nothing else.
  var salt: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformIdentityRecord? {
    let saveId = pigeonVar_list[0] as! String
    let salt = pigeonVar_list[1] as! FlutterStandardTypedData

    return PlatformIdentityRecord(
      saveId: saveId,
      salt: salt
    )
  }
  func toList() -> [Any?] {
    return [
      saveId,
      salt,
    ]
  }
  static func == (lhs: PlatformIdentityRecord, rhs: PlatformIdentityRecord) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.saveId, rhs.saveId) && MessagesPigeonInternal.deepEquals(lhs.salt, rhs.salt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformIdentityRecord")
    MessagesPigeonInternal.deepHash(value: saveId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: salt, hasher: &hasher)
  }

  public var description: String {
    return "PlatformIdentityRecord(saveId: \(String(describing: saveId)), salt: \(String(describing: salt)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSecureReadResult: Hashable, CustomStringConvertible {
  var status: PlatformSecureReadStatus
  /// Non-null exactly when [status] is `found`.
  var record: PlatformIdentityRecord? = nil
  /// The raw `OSStatus`, for a log line. Never shown to a player and never
  /// used to make a decision — the decision is [status].
  var osStatus: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSecureReadResult? {
    let status = pigeonVar_list[0] as! PlatformSecureReadStatus
    let record: PlatformIdentityRecord? = nilOrValue(pigeonVar_list[1])
    let osStatus: Int64? = nilOrValue(pigeonVar_list[2])

    return PlatformSecureReadResult(
      status: status,
      record: record,
      osStatus: osStatus
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      record,
      osStatus,
    ]
  }
  static func == (lhs: PlatformSecureReadResult, rhs: PlatformSecureReadResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.record, rhs.record) && MessagesPigeonInternal.deepEquals(lhs.osStatus, rhs.osStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformSecureReadResult")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: record, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: osStatus, hasher: &hasher)
  }

  public var description: String {
    return "PlatformSecureReadResult(status: \(String(describing: status)), record: \(String(describing: record)), osStatus: \(String(describing: osStatus)))"
  }
}

/// The result of applying `NSURLIsExcludedFromBackupKey`.
///
/// Reported per path rather than as one boolean, because a partial application
/// is the interesting case: a directory that is excluded while one file inside
/// it is not is still a ledger that travels.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformBackupExclusionReport: Hashable, CustomStringConvertible {
  /// Paths that now carry the exclusion, verified by reading the attribute
  /// back rather than by the setter returning without error.
  var excluded: [String]
  /// Paths that do not exist yet. Not a failure: `StorageLayout` names every
  /// file it *may* create, and the journal sidecar usually does not exist.
  var missing: [String]
  /// Paths that exist and could not be excluded. Each entry is
  /// `path\t<reason>`. This is the one condition that means the ledger would
  /// travel.
  var failed: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformBackupExclusionReport? {
    let excluded = pigeonVar_list[0] as! [String]
    let missing = pigeonVar_list[1] as! [String]
    let failed = pigeonVar_list[2] as! [String]

    return PlatformBackupExclusionReport(
      excluded: excluded,
      missing: missing,
      failed: failed
    )
  }
  func toList() -> [Any?] {
    return [
      excluded,
      missing,
      failed,
    ]
  }
  static func == (lhs: PlatformBackupExclusionReport, rhs: PlatformBackupExclusionReport) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.excluded, rhs.excluded) && MessagesPigeonInternal.deepEquals(lhs.missing, rhs.missing) && MessagesPigeonInternal.deepEquals(lhs.failed, rhs.failed)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformBackupExclusionReport")
    MessagesPigeonInternal.deepHash(value: excluded, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: missing, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: failed, hasher: &hasher)
  }

  public var description: String {
    return "PlatformBackupExclusionReport(excluded: \(String(describing: excluded)), missing: \(String(describing: missing)), failed: \(String(describing: failed)))"
  }
}

/// Read-back of what was actually configured, for tests and for a startup
/// self-check.
///
/// Exists because "we set the attribute" and "the attribute is set" are
/// different claims, and only the second one is worth anything after a
/// directory has been recreated by a restore.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSecureStoreDiagnostics: Hashable, CustomStringConvertible {
  /// The `kSecAttrAccessible` value on the stored item, as its raw string
  /// (`cku` for AfterFirstUnlockThisDeviceOnly, `ak` for WhenUnlocked, and so
  /// on). Null when no item is stored.
  ///
  /// A string rather than an enum because the assertion worth making is
  /// "exactly the constant we asked for", and an enum would silently fold an
  /// unexpected value into a known case.
  var keychainAccessibility: String? = nil
  var excludedPaths: [String]
  var notExcludedPaths: [String]
  var missingPaths: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSecureStoreDiagnostics? {
    let keychainAccessibility: String? = nilOrValue(pigeonVar_list[0])
    let excludedPaths = pigeonVar_list[1] as! [String]
    let notExcludedPaths = pigeonVar_list[2] as! [String]
    let missingPaths = pigeonVar_list[3] as! [String]

    return PlatformSecureStoreDiagnostics(
      keychainAccessibility: keychainAccessibility,
      excludedPaths: excludedPaths,
      notExcludedPaths: notExcludedPaths,
      missingPaths: missingPaths
    )
  }
  func toList() -> [Any?] {
    return [
      keychainAccessibility,
      excludedPaths,
      notExcludedPaths,
      missingPaths,
    ]
  }
  static func == (lhs: PlatformSecureStoreDiagnostics, rhs: PlatformSecureStoreDiagnostics) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.keychainAccessibility, rhs.keychainAccessibility) && MessagesPigeonInternal.deepEquals(lhs.excludedPaths, rhs.excludedPaths) && MessagesPigeonInternal.deepEquals(lhs.notExcludedPaths, rhs.notExcludedPaths) && MessagesPigeonInternal.deepEquals(lhs.missingPaths, rhs.missingPaths)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformSecureStoreDiagnostics")
    MessagesPigeonInternal.deepHash(value: keychainAccessibility, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: excludedPaths, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notExcludedPaths, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: missingPaths, hasher: &hasher)
  }

  public var description: String {
    return "PlatformSecureStoreDiagnostics(keychainAccessibility: \(String(describing: keychainAccessibility)), excludedPaths: \(String(describing: excludedPaths)), notExcludedPaths: \(String(describing: notExcludedPaths)), missingPaths: \(String(describing: missingPaths)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformSecureReadStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformSecureWriteStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PlatformIdentityRecord.fromList(self.readValue() as! [Any?])
    case 132:
      return PlatformSecureReadResult.fromList(self.readValue() as! [Any?])
    case 133:
      return PlatformBackupExclusionReport.fromList(self.readValue() as! [Any?])
    case 134:
      return PlatformSecureStoreDiagnostics.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformSecureReadStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformSecureWriteStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformIdentityRecord {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformSecureReadResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformBackupExclusionReport {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformSecureStoreDiagnostics {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SecureStoreHostApi {
  /// Reads the stored identity.
  ///
  /// Never throws for absence — absence is a typed status. It throws only when
  /// the platform itself misbehaves in a way that has no status.
  func readIdentity(completion: @escaping (Result<PlatformSecureReadResult, Error>) -> Void)
  /// Creates the identity. **Add-only.**
  ///
  /// There is no update method on this interface, and that is the enforcement
  /// mechanism for "never overwrite an existing key because a read failed": a
  /// caller that has just had a read fail cannot express an overwrite.
  func createIdentity(record: PlatformIdentityRecord, completion: @escaping (Result<PlatformSecureWriteStatus, Error>) -> Void)
  /// Removes the identity. Full reset only, and only from an explicit player
  /// action.
  func deleteIdentity(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Applies `NSURLIsExcludedFromBackupKey` to [directoryPath] and each of
  /// [filePaths], and verifies each by reading the attribute back.
  ///
  /// **Must be called on every launch.** The attribute lives on the filesystem
  /// node, not on the app: if the directory is deleted and recreated — by a
  /// restore, by a reinstall, by our own `ensureExists` after a wipe — the
  /// exclusion is gone and nothing reports it.
  func applyBackupExclusions(directoryPath: String, filePaths: [String], completion: @escaping (Result<PlatformBackupExclusionReport, Error>) -> Void)
  /// Re-applies `NSURLIsExcludedFromBackupKey` to [paths] and nothing else.
  ///
  /// **Why a second, narrower method.** Apple documents
  /// `NSURLIsExcludedFromBackupKey` as a resource value on the filesystem node,
  /// and resource values do not follow a path: a replacement, an atomic write,
  /// a rename over the top, or a delete-and-recreate all leave the path
  /// pointing at a *different* node, which carries whatever attributes it was
  /// born with — none.
  ///
  /// The save layout does all of those. `FileLedgerJournal.replaceLines` writes
  /// a sidecar and renames it over the journal, so after every compaction the
  /// journal path names a node that has never been excluded. The snapshot slots
  /// are created on their first write. So a once-at-launch application is
  /// correct until the first commit and silently wrong after it.
  ///
  /// Separate from [applyBackupExclusions] because that one is the launch
  /// sweep: it takes the directory as well, and reports the whole layout. This
  /// is the per-write call — a list of the paths a single operation just
  /// touched, no directory, so it stays cheap enough to sit on the commit path.
  /// Two `setResourceValues` round trips per file, against an fsync.
  ///
  /// Idempotent. Paths that do not exist come back as `missing`, not `failed`.
  func reapplyBackupExclusions(paths: [String], completion: @escaping (Result<PlatformBackupExclusionReport, Error>) -> Void)
  /// Reads back what is actually configured. Diagnostics only.
  func readDiagnostics(paths: [String], completion: @escaping (Result<PlatformSecureStoreDiagnostics, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SecureStoreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SecureStoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SecureStoreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Reads the stored identity.
    ///
    /// Never throws for absence — absence is a typed status. It throws only when
    /// the platform itself misbehaves in a way that has no status.
    let readIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.readIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readIdentityChannel.setMessageHandler { _, reply in
        api.readIdentity { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readIdentityChannel.setMessageHandler(nil)
    }
    /// Creates the identity. **Add-only.**
    ///
    /// There is no update method on this interface, and that is the enforcement
    /// mechanism for "never overwrite an existing key because a read failed": a
    /// caller that has just had a read fail cannot express an overwrite.
    let createIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.createIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createIdentityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recordArg = args[0] as! PlatformIdentityRecord
        api.createIdentity(record: recordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createIdentityChannel.setMessageHandler(nil)
    }
    /// Removes the identity. Full reset only, and only from an explicit player
    /// action.
    let deleteIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.deleteIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteIdentityChannel.setMessageHandler { _, reply in
        api.deleteIdentity { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteIdentityChannel.setMessageHandler(nil)
    }
    /// Applies `NSURLIsExcludedFromBackupKey` to [directoryPath] and each of
    /// [filePaths], and verifies each by reading the attribute back.
    ///
    /// **Must be called on every launch.** The attribute lives on the filesystem
    /// node, not on the app: if the directory is deleted and recreated — by a
    /// restore, by a reinstall, by our own `ensureExists` after a wipe — the
    /// exclusion is gone and nothing reports it.
    let applyBackupExclusionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.applyBackupExclusions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyBackupExclusionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let directoryPathArg = args[0] as! String
        let filePathsArg = args[1] as! [String]
        api.applyBackupExclusions(directoryPath: directoryPathArg, filePaths: filePathsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      applyBackupExclusionsChannel.setMessageHandler(nil)
    }
    /// Re-applies `NSURLIsExcludedFromBackupKey` to [paths] and nothing else.
    ///
    /// **Why a second, narrower method.** Apple documents
    /// `NSURLIsExcludedFromBackupKey` as a resource value on the filesystem node,
    /// and resource values do not follow a path: a replacement, an atomic write,
    /// a rename over the top, or a delete-and-recreate all leave the path
    /// pointing at a *different* node, which carries whatever attributes it was
    /// born with — none.
    ///
    /// The save layout does all of those. `FileLedgerJournal.replaceLines` writes
    /// a sidecar and renames it over the journal, so after every compaction the
    /// journal path names a node that has never been excluded. The snapshot slots
    /// are created on their first write. So a once-at-launch application is
    /// correct until the first commit and silently wrong after it.
    ///
    /// Separate from [applyBackupExclusions] because that one is the launch
    /// sweep: it takes the directory as well, and reports the whole layout. This
    /// is the per-write call — a list of the paths a single operation just
    /// touched, no directory, so it stays cheap enough to sit on the commit path.
    /// Two `setResourceValues` round trips per file, against an fsync.
    ///
    /// Idempotent. Paths that do not exist come back as `missing`, not `failed`.
    let reapplyBackupExclusionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.reapplyBackupExclusions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reapplyBackupExclusionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathsArg = args[0] as! [String]
        api.reapplyBackupExclusions(paths: pathsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      reapplyBackupExclusionsChannel.setMessageHandler(nil)
    }
    /// Reads back what is actually configured. Diagnostics only.
    let readDiagnosticsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.stride_secure_store.SecureStoreHostApi.readDiagnostics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readDiagnosticsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathsArg = args[0] as! [String]
        api.readDiagnostics(paths: pathsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readDiagnosticsChannel.setMessageHandler(nil)
    }
  }
}
