// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.projectstride.stride_health

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Mirrors `StepAuthorization` in stride_core. */
enum class PlatformAuthorization(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  UNAVAILABLE(2);

  companion object {
    fun ofRaw(raw: Int): PlatformAuthorization? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `CursorStatus` in stride_core. */
enum class PlatformCursorStatus(val raw: Int) {
  VALID(0),
  INVALIDATED(1);

  companion object {
    fun ofRaw(raw: Int): PlatformCursorStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An authoritative re-read of a bounded window, sent only when the cursor was
 * invalidated. See `StepRescan` in stride_core for the recovery strategy.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformRescan (
  /**
   * Start of the rescanned window — the watermark the caller supplied,
   * clamped by the adapter to its maximum window.
   */
  val windowStartMillis: Long,
  val windowEndMillis: Long,
  /**
   * The authoritative total for the window. A total, not a delta: after cursor
   * loss only an absolute figure can be reconciled against what was already
   * granted.
   */
  val windowTotal: Long,
  /**
   * True when the window was clamped, leaving an unreachable gap. Those steps
   * are recorded, never granted — inventing progress is worse than missing it.
   */
  val truncated: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformRescan {
      val windowStartMillis = pigeonVar_list[0] as Long
      val windowEndMillis = pigeonVar_list[1] as Long
      val windowTotal = pigeonVar_list[2] as Long
      val truncated = pigeonVar_list[3] as Boolean
      return PlatformRescan(windowStartMillis, windowEndMillis, windowTotal, truncated)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      windowStartMillis,
      windowEndMillis,
      windowTotal,
      truncated,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformRescan
    return MessagesPigeonUtils.deepEquals(this.windowStartMillis, other.windowStartMillis) && MessagesPigeonUtils.deepEquals(this.windowEndMillis, other.windowEndMillis) && MessagesPigeonUtils.deepEquals(this.windowTotal, other.windowTotal) && MessagesPigeonUtils.deepEquals(this.truncated, other.truncated)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowStartMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowEndMillis)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.windowTotal)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.truncated)
    return result
  }
  override fun toString(): String {
    return "PlatformRescan(windowStartMillis=$windowStartMillis, windowEndMillis=$windowEndMillis, windowTotal=$windowTotal, truncated=$truncated)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformFetchResult (
  val status: PlatformCursorStatus,
  /** A true delta only when [status] is `valid`. Meaningless otherwise. */
  val newSteps: Long,
  /**
   * Steps removed by corrections since the cursor. Information, not an
   * instruction — reconciliation never revokes granted progress.
   */
  val deletedSteps: Long,
  /**
   * Opaque. An archived HKQueryAnchor on iOS, a changes token on Android.
   * The caller stores and returns it without inspecting it, and persists it
   * only after the resulting batch is committed to the ledger.
   */
  val cursor: ByteArray? = null,
  val rescan: PlatformRescan? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformFetchResult {
      val status = pigeonVar_list[0] as PlatformCursorStatus
      val newSteps = pigeonVar_list[1] as Long
      val deletedSteps = pigeonVar_list[2] as Long
      val cursor = pigeonVar_list[3] as ByteArray?
      val rescan = pigeonVar_list[4] as PlatformRescan?
      return PlatformFetchResult(status, newSteps, deletedSteps, cursor, rescan)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      newSteps,
      deletedSteps,
      cursor,
      rescan,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformFetchResult
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.newSteps, other.newSteps) && MessagesPigeonUtils.deepEquals(this.deletedSteps, other.deletedSteps) && MessagesPigeonUtils.deepEquals(this.cursor, other.cursor) && MessagesPigeonUtils.deepEquals(this.rescan, other.rescan)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.newSteps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deletedSteps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cursor)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rescan)
    return result
  }
  override fun toString(): String {
    return "PlatformFetchResult(status=$status, newSteps=$newSteps, deletedSteps=$deletedSteps, cursor=${cursor?.contentToString()}, rescan=$rescan)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformAuthorization.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformCursorStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformRescan.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformFetchResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformAuthorization -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformCursorStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformRescan -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PlatformFetchResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HealthHostApi {
  /**
   * Whether the platform's health service is present and usable. False on
   * Android without Health Connect installed — a normal state, not an error.
   */
  fun isAvailable(): Boolean
  fun requestAuthorization(callback: (Result<PlatformAuthorization>) -> Unit)
  /**
   * Fetch steps since [cursor]. [watermarkMillis] bounds the rescan window if
   * the cursor turns out to be invalid.
   */
  fun fetchNewSteps(cursor: ByteArray?, watermarkMillis: Long?, callback: (Result<PlatformFetchResult>) -> Unit)

  companion object {
    /** The codec used by HealthHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HealthHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HealthHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.stride_health.HealthHostApi.isAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isAvailable())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.stride_health.HealthHostApi.requestAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestAuthorization{ result: Result<PlatformAuthorization> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.stride_health.HealthHostApi.fetchNewSteps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cursorArg = args[0] as ByteArray?
            val watermarkMillisArg = args[1] as Long?
            api.fetchNewSteps(cursorArg, watermarkMillisArg) { result: Result<PlatformFetchResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
